load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_library", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")

rust_package()

rust_library(
    name = "signalbox_tools_git",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [
        "src/tests/fixtures/git-conformance/contended-lock",
        "src/tests/fixtures/git-conformance/contended-ref",
        "src/tests/fixtures/git-conformance/contended-result",
        "src/tests/fixtures/git-conformance/loose-topic",
        "src/tests/fixtures/git-conformance/packed-refs.bin",
        "src/tests/fixtures/git-conformance/packed-replacement-record",
        "src/tests/fixtures/git-conformance/resolved-topic",
        "src/tests/fixtures/git-conformance/sha256-pack-checksum",
        "src/tests/fixtures/git-conformance/sha256-pack-object-ids",
        "src/tests/fixtures/git-conformance/update-ref-after",
        "src/tests/fixtures/git-conformance/update-ref-before",
        "src/tests/fixtures/git-conformance/update-ref-lock-state",
    ],
    crate_features = [],
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = ["//crates/derive:signalbox_derive"] + all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//crates/application:signalbox_application",
        "//crates/domain:signalbox_domain",
        "//crates/tool-contract:signalbox_tool_contract",
        "//crates/tools-workspace:signalbox_tools_workspace",
    ] + all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    compile_data = glob(["src/tests/fixtures/**"]),
    crate = ":signalbox_tools_git",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_doc(
    name = "api_json",
    crate = ":signalbox_tools_git",
    rustdoc_flags = [
        "-Z",
        "unstable-options",
        "--output-format",
        "json",
    ],
    visibility = ["//:__pkg__"],
)
