load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_doc_test", "rust_integration_test", "rust_quality_tests", "rust_unit_test")

CRATE_DEPS = [
    ":signalbox_file_media_adapters_text",
    "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
    "//crates/file-media-runtime:signalbox_file_media_runtime",
]

rust_package()

rust_library(
    name = "signalbox_file_media_adapters_text",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_binary(
    name = "signalbox-file-media-text-worker",
    crate_root = "src/bin/signalbox-file-media-text-worker.rs",
    deps = CRATE_DEPS,
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_file_media_adapters_text",
)

rust_unit_test(
    name = "signalbox_file_media_text_worker_unit_tests",
    crate = ":signalbox-file-media-text-worker",
)

rust_integration_test(
    name = "adapters",
    size = "small",
    srcs = glob(["tests/**/*.rs"]),
    crate_root = "tests/adapters.rs",
    deps = CRATE_DEPS,
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_file_media_adapters_text",
)

rust_quality_tests(documented_crates = [
    ":signalbox_file_media_adapters_text",
    ":signalbox-file-media-text-worker",
])
