const labels = new Map<string, string>(
  Object.entries({
    anthropic: 'Anthropic',
    open_ai: 'OpenAI',
    codex_cli: 'Codex CLI',
    standard_only: 'Standard only',
    default: 'Default',
    priority: 'Priority',
    flex: 'Flex',
    scale: 'Scale',
    fast: 'Fast',
    abandoned: 'Abandoned',
    accepted_input: 'Accepted message',
    achieved: 'Achieved',
    achieved_declared: 'Completion reported',
    achieved_verified: 'Completion verified',
    activated: 'Started',
    active: 'Active',
    adopted: 'Adopted',
    alias: 'Alias',
    already_terminal: 'Already finished',
    ambiguous: 'Outcome unknown',
    approval_judge: 'Approval judge',
    approve: 'Approve',
    assistant_transcript: 'Assistant-role message',
    attachment: 'Attachment',
    attachment_filename: 'Attachment filename',
    attachment_media_metadata: 'Attachment details',
    audio: 'Audio',
    authorization_required: 'Needs authorization',
    auto: 'Auto',
    awaiting_approval: 'Needs approval',
    awaiting_child: 'Waiting for child session',
    awaiting_model_call_recovery: 'Model call needs recovery',
    awaiting_reconciliation: 'Turn needs recovery',
    awaiting_runner_recovery: 'Runner needs recovery',
    awaiting_tool_approval: 'Needs tool approval',
    awaiting_tool_recovery: 'Tool needs recovery',
    background: 'Background',
    base_advanced: 'Base branch updated',
    blob: 'File',
    blocked: 'Blocked',
    bound: 'Bound',
    branch_workflow_run_completed: 'Branch workflow run completed',
    browser_native: 'Original',
    cancel: 'Cancel',
    cancellation_requested: 'Cancellation requested',
    cancelled: 'Cancelled',
    check_run_completed: 'Check run completed',
    checks_completed: 'Checks completed',
    child_cancelled: 'Child cancelled',
    child_completed: 'Child completed',
    child_execution_failed: 'Child execution failed',
    child_failed: 'Child failed',
    child_lifecycle_disposition: 'Child session status',
    child_result: 'Child result',
    child_result_unavailable: 'Child result unavailable',
    child_spawned: 'Child session created',
    child_stopped: 'Child stopped',
    child_waiting: 'Child waiting',
    claude_code_session_jsonl_v1: 'Claude Code, converter 1',
    claude_code_session_jsonl_v2: 'Claude Code, converter 2',
    code: 'Code',
    codex_rollout_jsonl_v1: 'Codex rollout, converter 1',
    command_settled: 'Command finished',
    commissioned: 'Assigned',
    completed: 'Completed',
    condensed: 'Condensed',
    configuration_unavailable: 'Pricing unavailable',
    connected: 'Connected',
    context_compacted: 'Context summarized',
    context_compaction: 'Context summary',
    continue_running: 'Continue running',
    crash_lost: 'Lost after crash',
    created: 'Created',
    credential_rejected: 'Credentials rejected',
    decide_approval: 'Needs approval',
    delegate: 'Delegate',
    delegated: 'Delegated',
    delegation_update: 'Delegation update',
    delegation_wake: 'Delegated session resumed',
    deny: 'Deny',
    derivative: 'Preview',
    derived_artifact: 'Generated content',
    derived_text_artifact: 'Derived text',
    direct: 'Direct',
    disabled: 'Disabled',
    dispatched: 'Dispatched',
    document: 'Document',
    download: 'Download',
    effect_free: 'No external changes',
    enabled: 'Enabled',
    estimated: 'Estimated',
    execution_failed: 'Execution failed',
    execution_failure: 'Execution failed',
    external_change_required: 'Needs an external change',
    external_effect: 'May change external systems',
    failed: 'Failed',
    failed_retryable: 'Failed; retry available',
    failed_structural: 'Failed, retrying the same input will not help',
    failed_unknown: 'Failed; cause unknown',
    finish_check_failed: 'Completion check failed',
    foreground: 'Foreground',
    fork: 'Fork',
    full: 'Full',
    goal: 'Goal',
    goal_changed: 'Goal changed',
    goal_turn_retired: 'Turn retired before it started',
    head_changed: 'Latest commit changed',
    high: 'High',
    human: 'Human',
    idle: 'Idle',
    image: 'Image',
    in_flight: 'In progress',
    incomplete_cache_axes: 'Cache token counts incomplete',
    injection_settled: 'Message delivery finished',
    input_accepted: 'Message accepted',
    interactive: 'Interactive',
    invalid_arguments: 'Invalid arguments',
    invalid_cache_breakdown: 'Invalid cache token counts',
    invalid_request: 'Invalid request',
    keep_running: 'Keep running',
    known_failed: 'Failed',
    labeled: 'Labeled',
    lost: 'Disconnected',
    low: 'Low',
    max: 'Maximum',
    media_placeholder: 'Media',
    medium: 'Medium',
    mergeable_state_changed: 'Merge status changed',
    message_content_absent: 'No message content',
    message_wake: 'Resumed after message',
    metered_equivalent: 'Equivalent metered cost',
    minimal: 'Minimal',
    model_call: 'Model call',
    model_call_transition: 'Model call updated',
    no_token_evidence: 'No token counts',
    none: 'None',
    overloaded: 'Server busy',
    parent_cancelled_with_descendants: 'Parent and child sessions cancelled',
    parent_stopped_with_descendants: 'Parent and child sessions stopped',
    parked: 'Parked',
    permission_denied: 'Permission denied',
    pinned: 'Assigned',
    policy: 'Policy',
    preauthorization_rejected: 'Authorization rejected',
    prepared: 'Prepared',
    preview: 'Preview',
    proposed: 'Proposed',
    provide_goal_need: 'Needs input',
    provider_internal: 'Provider error',
    pull_request_closed: 'Pull request closed',
    pull_request_merged: 'Pull request merged',
    pull_request_opened: 'Pull request opened',
    queued: 'Queued',
    quota_exhausted: 'Quota reached',
    rate_limited: 'Rate limit reached',
    reaction_changed: 'Reaction changed',
    real: 'Actual',
    reconcile_turn: 'Recover turn',
    recovering: 'Recovering',
    recovery_required: 'Recovery needed',
    redacted_thinking: 'Hidden thinking',
    refused: 'Refused',
    released: 'Released',
    replaced: 'Replaced',
    reported: 'Reported',
    repository_watch: 'Repository watch',
    request_too_large: 'Request too large',
    result_contains_null: 'Result contains null characters',
    result_returned: 'Result returned',
    result_too_large: 'Result too large',
    result_wake: 'Resumed after result',
    results: 'Results',
    results_projected: 'Results available',
    resume: 'Resume',
    resumed: 'Resumed',
    retired: 'Retired before starting',
    review_submitted: 'Review submitted',
    runner: 'Runner',
    runner_abandoned: 'Abandoned',
    runner_lost: 'Runner disconnected',
    runner_lost_before_pin: 'Disconnected before assignment',
    runner_state_transition: 'Runner updated',
    running: 'Running',
    sandboxed: 'Sandboxed',
    session: 'Session',
    session_closed: 'Session closed',
    session_created: 'Session created',
    session_message: 'Session message',
    session_metadata: 'Session details',
    session_model_settings_changed: 'Session model settings changed',
    session_ownership_changed: 'Session ownership changed',
    session_state_changed: 'Session state changed',
    session_terminal: 'Session finished',
    session_transcript_entry: 'Session message',
    settled: 'Done',
    shutdown: 'Shut down',
    source_event: 'Source event',
    source_message_block: 'Source message',
    steering_input: 'Steering message',
    stop: 'Stop',
    stopped: 'Stopped',
    superseded: 'Superseded',
    suspect: 'Connection uncertain',
    target_not_found: 'Model not found',
    terminal: 'Finished',
    terminalized: 'Finished',
    text: 'Text',
    thinking: 'Thinking',
    thread_opened: 'Thread opened',
    thread_resolved: 'Thread resolved',
    thumbnail: 'Thumbnail',
    tool_approval_decided: 'Tool approval decided',
    tool_arguments: 'Tool arguments',
    tool_attempt: 'Tool attempt',
    tool_batch_transition: 'Tool batch updated',
    tool_call: 'Tool call',
    tool_request: 'Tool request',
    tool_result: 'Tool output',
    turn: 'Turn',
    turn_activated: 'Turn started',
    turn_cancelled: 'Turn cancelled',
    turn_completed: 'Turn completed',
    turn_failed: 'Turn failed',
    turn_model_settings_resolved: 'Turn model settings selected',
    turn_reconciliation_required: 'Turn needs recovery',
    turn_refused: 'Turn refused',
    turn_transcript_entry: 'Turn message',
    ultra: 'Ultra',
    unavailable: 'Unavailable',
    unknown_input_semantics: 'Input token accounting unknown',
    unknown_tool: 'Unknown tool',
    unlabeled: 'Unlabeled',
    unpinned: 'Unassigned',
    unrecognized: 'Unknown error',
    unsandboxed: 'Unsandboxed',
    user: 'User',
    user_input_required: 'Needs input',
    user_override: 'User override',
    user_stopped: 'Stopped by user',
    user_transcript: 'User-role message',
    video: 'Video',
    waiting: 'Waiting',
    workflow: 'Workflow',
    working_directory_changed: 'Working directory changed',
    xhigh: 'Extra high',
  }),
)

export const enumLabel = (value: string): string => labels.get(value) ?? value
