load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_doc_test", "rust_integration_test", "rust_quality_tests", "rust_unit_test")

rust_package()

rust_library(
    name = "signalbox_file_media_adapters_audio",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_binary(
    name = "signalbox-file-media-audio-worker",
    crate_root = "src/bin/signalbox-file-media-audio-worker.rs",
    deps = [
        ":signalbox_file_media_adapters_audio",
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_file_media_adapters_audio",
)

rust_unit_test(
    name = "signalbox_file_media_audio_worker_unit_tests",
    crate = ":signalbox-file-media-audio-worker",
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_file_media_adapters_audio",
)

rust_integration_test(
    name = "adapters",
    srcs = glob(["tests/**/*.rs"]),
    args = ["--test-threads=4"],
    crate_root = "tests/adapters.rs",
    data = glob(
        ["tests/**"],
        allow_empty = True,
        exclude = ["tests/**/*.rs"],
    ) + [":signalbox-file-media-audio-worker"],
    env = {
        "CI": "true",
        "NEXTEST_BIN_EXE_signalbox_file_media_audio_worker": "$(rootpath :signalbox-file-media-audio-worker)",
    },
    env_inherit = ["SIGNALBOX_FILE_MEDIA_CGROUP_ROOT"],
    rustc_env = {
        "CARGO_MANIFEST_DIR": "crates/file-media-adapters-audio",
        "CARGO_BIN_EXE_signalbox-file-media-audio-worker": "$(rootpath :signalbox-file-media-audio-worker)",
    },
    tags = [
        "external",
        "manual",
        "no-sandbox",
    ],
    deps = [
        "//crates/file-media-adapters-audio:signalbox_file_media_adapters_audio",
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
        "//crates/test-bin:signalbox_test_bin",
    ],
)

rust_quality_tests(documented_crates = [
    ":signalbox_file_media_adapters_audio",
    ":signalbox-file-media-audio-worker",
])
