//! Deployment-owned blob stores and semantic write routes.

use std::{
    collections::{BTreeMap, BTreeSet},
    error::Error,
    fmt,
    path::{Path, PathBuf},
    sync::Arc,
};

use signalbox_blob_store::BlobStoreName;
pub use signalbox_blob_store::MAX_BLOB_STORES;
use toml_edit::{Item, Table};
use url::{Host, Url};
use uuid::Uuid;

const MAX_S3_LOCATION_BYTES: usize = 255;

/// Semantic purpose used only to select the store for a new write.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum BlobStorageClass {
    /// Bytes attached to a user-role message.
    UserAttachment,
    /// Bytes produced or retained by a tool.
    ToolArtifact,
    /// Raw source bytes retained by conversation import.
    ImportedSource,
    /// Assets generated by a model-facing operation.
    GeneratedArtifact,
}

/// Adapter-specific configuration for one durable store identity.
#[derive(Clone, Eq, PartialEq)]
pub enum BlobStoreConfiguration {
    /// A filesystem namespace rooted at one absolute directory.
    Filesystem {
        /// Canonical deployment identity for this physical namespace.
        namespace_id: Uuid,
        /// Absolute root under which deterministic object keys are resolved.
        root_directory: PathBuf,
    },
    /// One path-style S3-compatible bucket and its explicit credential file.
    S3 {
        /// Canonical deployment identity for this physical namespace.
        namespace_id: Uuid,
        /// Absolute HTTP(S) service endpoint.
        endpoint: Url,
        /// Explicit signing region.
        region: Arc<str>,
        /// Explicit bucket name.
        bucket: Arc<str>,
        /// Absolute file containing strict static credentials.
        credentials_file: PathBuf,
    },
}

impl fmt::Debug for BlobStoreConfiguration {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(match self {
            Self::Filesystem { .. } => "BlobStoreConfiguration::Filesystem { .. }",
            Self::S3 { .. } => "BlobStoreConfiguration::S3 { .. }",
        })
    }
}

impl BlobStoreConfiguration {
    /// Returns the canonical deployment identity for this physical namespace.
    pub const fn namespace_id(&self) -> Uuid {
        match self {
            Self::Filesystem { namespace_id, .. } | Self::S3 { namespace_id, .. } => *namespace_id,
        }
    }

    /// Returns the filesystem root when this is a filesystem store.
    pub fn filesystem_root(&self) -> Option<&Path> {
        match self {
            Self::Filesystem { root_directory, .. } => Some(root_directory),
            Self::S3 { .. } => None,
        }
    }

    /// Returns S3 construction values when this is an S3 store.
    pub fn s3(&self) -> Option<(&Url, &str, &str, &Path)> {
        match self {
            Self::Filesystem { .. } => None,
            Self::S3 {
                endpoint,
                region,
                bucket,
                credentials_file,
                ..
            } => Some((endpoint, region, bucket, credentials_file)),
        }
    }
}

/// Validated optional blob-storage section from the daemon catalog.
#[derive(Clone, Eq, PartialEq)]
pub struct BlobStorageConfiguration {
    staging_directory: PathBuf,
    max_blob_bytes: u64,
    stores: BTreeMap<BlobStoreName, BlobStoreConfiguration>,
    routes: BTreeMap<BlobStorageClass, BlobStoreName>,
}

impl fmt::Debug for BlobStorageConfiguration {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BlobStorageConfiguration")
            .field("staging_directory", &"<redacted>")
            .field("max_blob_bytes", &self.max_blob_bytes)
            .field("store_count", &self.stores.len())
            .field("route_count", &self.routes.len())
            .finish()
    }
}

impl BlobStorageConfiguration {
    pub(crate) fn parse(
        item: Option<&Item>,
        minimum_blob_bytes: u64,
    ) -> Result<Option<Self>, BlobStorageConfigurationError> {
        item.map(|item| parse_configuration(item, minimum_blob_bytes))
            .transpose()
    }

    /// Returns the absolute directory used for connection-local upload spools.
    pub fn staging_directory(&self) -> &Path {
        &self.staging_directory
    }

    /// Returns the deployment ceiling enforced before and during ingest.
    pub const fn max_blob_bytes(&self) -> u64 {
        self.max_blob_bytes
    }

    /// Returns stores in canonical durable-name order.
    pub fn stores(&self) -> impl Iterator<Item = (&BlobStoreName, &BlobStoreConfiguration)> + '_ {
        self.stores.iter()
    }

    /// Resolves one already-recorded durable store identity.
    pub fn store(&self, name: &BlobStoreName) -> Option<&BlobStoreConfiguration> {
        self.stores.get(name)
    }

    /// Resolves one configured deployment binding without consulting placement.
    pub fn namespace_id(&self, name: &BlobStoreName) -> Option<Uuid> {
        self.store(name).map(BlobStoreConfiguration::namespace_id)
    }

    /// Resolves the store selected for one new semantic use.
    pub fn route(&self, class: BlobStorageClass) -> (&BlobStoreName, &BlobStoreConfiguration) {
        let name = &self.routes[&class];
        (name, &self.stores[name])
    }

    /// Returns every store name some semantic write route currently selects.
    ///
    /// Reading the parsed route map keeps callers from restating the class
    /// inventory, so a store named only by a later class stays routed.
    pub fn routed_stores(&self) -> impl Iterator<Item = &BlobStoreName> + '_ {
        self.routes.values()
    }

    /// Reports whether every durable store identity remains configured.
    pub fn resolves_recorded_stores<'a>(
        &self,
        recorded: impl IntoIterator<Item = &'a BlobStoreName>,
    ) -> bool {
        recorded
            .into_iter()
            .all(|name| self.stores.contains_key(name))
    }
}

/// The optional blob-storage section was malformed or internally inconsistent.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BlobStorageConfigurationError;

impl fmt::Display for BlobStorageConfigurationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("model configuration contains invalid blob-storage settings")
    }
}

impl Error for BlobStorageConfigurationError {}

fn parse_configuration(
    item: &Item,
    minimum_blob_bytes: u64,
) -> Result<BlobStorageConfiguration, BlobStorageConfigurationError> {
    let table = item.as_table().ok_or(BlobStorageConfigurationError)?;
    reject_unknown_fields(
        table,
        &[
            "version",
            "staging_directory",
            "max_blob_bytes",
            "stores",
            "routes",
        ],
    )?;
    if table.get("version").and_then(Item::as_integer) != Some(1) {
        return Err(BlobStorageConfigurationError);
    }
    let staging_directory = absolute_path(table, "staging_directory")?;
    let max_blob_bytes = table
        .get("max_blob_bytes")
        .and_then(Item::as_integer)
        .and_then(|value| u64::try_from(value).ok())
        .filter(|value| *value > 0)
        .ok_or(BlobStorageConfigurationError)?;
    if max_blob_bytes < minimum_blob_bytes {
        return Err(BlobStorageConfigurationError);
    }
    let store_tables = table
        .get("stores")
        .and_then(Item::as_array_of_tables)
        .filter(|stores| !stores.is_empty() && stores.len() <= MAX_BLOB_STORES)
        .ok_or(BlobStorageConfigurationError)?;
    let mut stores = BTreeMap::new();
    let mut namespace_ids = BTreeSet::new();
    for store_table in store_tables {
        let name = BlobStoreName::try_new(required_string(store_table, "name")?)
            .map_err(|_| BlobStorageConfigurationError)?;
        let store = parse_store(store_table)?;
        if !namespace_ids.insert(store.namespace_id()) {
            return Err(BlobStorageConfigurationError);
        }
        if stores.insert(name, store).is_some() {
            return Err(BlobStorageConfigurationError);
        }
    }
    let routes = parse_routes(table.get("routes"), stores.keys().cloned().collect())?;
    Ok(BlobStorageConfiguration {
        staging_directory,
        max_blob_bytes,
        stores,
        routes,
    })
}

fn parse_store(table: &Table) -> Result<BlobStoreConfiguration, BlobStorageConfigurationError> {
    let namespace_text = required_string(table, "namespace_id")?;
    let namespace_id =
        Uuid::parse_str(namespace_text).map_err(|_| BlobStorageConfigurationError)?;
    if namespace_text != namespace_id.hyphenated().to_string() {
        return Err(BlobStorageConfigurationError);
    }
    match required_string(table, "kind")? {
        "filesystem" => {
            reject_unknown_fields(table, &["name", "namespace_id", "kind", "root_directory"])?;
            Ok(BlobStoreConfiguration::Filesystem {
                namespace_id,
                root_directory: absolute_path(table, "root_directory")?,
            })
        }
        "s3" => {
            reject_unknown_fields(
                table,
                &[
                    "name",
                    "namespace_id",
                    "kind",
                    "endpoint",
                    "region",
                    "bucket",
                    "credentials_file",
                ],
            )?;
            let endpoint = parse_s3_endpoint(required_string(table, "endpoint")?)?;
            let region = bounded_s3_text(required_string(table, "region")?)?;
            let bucket = bounded_s3_text(required_string(table, "bucket")?)?;
            Ok(BlobStoreConfiguration::S3 {
                namespace_id,
                endpoint,
                region,
                bucket,
                credentials_file: absolute_path(table, "credentials_file")?,
            })
        }
        _ => Err(BlobStorageConfigurationError),
    }
}

fn parse_routes(
    item: Option<&Item>,
    store_names: BTreeSet<BlobStoreName>,
) -> Result<BTreeMap<BlobStorageClass, BlobStoreName>, BlobStorageConfigurationError> {
    let table = item
        .and_then(Item::as_table)
        .ok_or(BlobStorageConfigurationError)?;
    reject_unknown_fields(
        table,
        &[
            "user_attachment",
            "tool_artifact",
            "imported_source",
            "generated_artifact",
        ],
    )?;
    let pairs = [
        (BlobStorageClass::UserAttachment, "user_attachment"),
        (BlobStorageClass::ToolArtifact, "tool_artifact"),
        (BlobStorageClass::ImportedSource, "imported_source"),
        (BlobStorageClass::GeneratedArtifact, "generated_artifact"),
    ];
    pairs
        .into_iter()
        .map(|(class, field)| {
            let name = BlobStoreName::try_new(required_string(table, field)?)
                .map_err(|_| BlobStorageConfigurationError)?;
            if !store_names.contains(&name) {
                return Err(BlobStorageConfigurationError);
            }
            Ok((class, name))
        })
        .collect()
}

fn parse_s3_endpoint(value: &str) -> Result<Url, BlobStorageConfigurationError> {
    let endpoint = Url::parse(value).map_err(|_| BlobStorageConfigurationError)?;
    if !endpoint.username().is_empty()
        || endpoint.password().is_some()
        || endpoint.query().is_some()
        || endpoint.fragment().is_some()
    {
        return Err(BlobStorageConfigurationError);
    }
    match endpoint.scheme() {
        "https" => {}
        "http" if endpoint.host().is_some_and(literal_host_is_loopback) => {}
        _ => return Err(BlobStorageConfigurationError),
    }
    Ok(endpoint)
}

fn literal_host_is_loopback(host: Host<&str>) -> bool {
    match host {
        Host::Ipv4(address) => address.is_loopback(),
        Host::Ipv6(address) => address.is_loopback(),
        Host::Domain(_) => false,
    }
}

fn bounded_s3_text(value: &str) -> Result<Arc<str>, BlobStorageConfigurationError> {
    if value.is_empty() || value.len() > MAX_S3_LOCATION_BYTES || !value.is_ascii() {
        Err(BlobStorageConfigurationError)
    } else {
        Ok(Arc::from(value))
    }
}

fn absolute_path(table: &Table, field: &str) -> Result<PathBuf, BlobStorageConfigurationError> {
    let value = required_string(table, field)?;
    let path = PathBuf::from(value);
    if path.is_absolute() && !value.contains('\0') {
        Ok(path)
    } else {
        Err(BlobStorageConfigurationError)
    }
}

fn required_string<'a>(
    table: &'a Table,
    field: &str,
) -> Result<&'a str, BlobStorageConfigurationError> {
    table
        .get(field)
        .and_then(Item::as_str)
        .ok_or(BlobStorageConfigurationError)
}

fn reject_unknown_fields(
    table: &Table,
    admitted: &[&str],
) -> Result<(), BlobStorageConfigurationError> {
    if table.iter().all(|(name, _)| admitted.contains(&name)) {
        Ok(())
    } else {
        Err(BlobStorageConfigurationError)
    }
}

#[cfg(test)]
mod tests {
    use std::{fmt::Write, str::FromStr};

    use signalbox_blob_store::BlobStoreName;
    use toml_edit::DocumentMut;

    use super::{BlobStorageClass, BlobStorageConfiguration, MAX_BLOB_STORES};

    const MAX_BYTES_FIXTURE: u64 = 1_099_511_627_776;
    const PRIMARY_NAME_FIXTURE: &str = "primary";
    const PRIMARY_ROOT_FIXTURE: &str = "/var/lib/signalbox/blobs";
    const S3_ENDPOINT_HOST_FIXTURE: &str = "objects.example.test";
    const S3_BUCKET_FIXTURE: &str = "signalbox-archive";
    const STORE_COUNT_FIXTURE: usize = 2;

    const VALID: &str = r#"
[blob_storage]
version = 1
staging_directory = "/var/lib/signalbox/blob-staging"
max_blob_bytes = 1099511627776

[[blob_storage.stores]]
name = "primary"
namespace_id = "5a100001-0000-0000-0000-000000000001"
kind = "filesystem"
root_directory = "/var/lib/signalbox/blobs"

[[blob_storage.stores]]
name = "archive"
namespace_id = "5a100001-0000-0000-0000-000000000002"
kind = "s3"
endpoint = "https://objects.example.test"
region = "us-test-1"
bucket = "signalbox-archive"
credentials_file = "/run/credentials/signalbox-archive"

[blob_storage.routes]
user_attachment = "primary"
tool_artifact = "archive"
imported_source = "primary"
generated_artifact = "archive"
"#;

    fn parse(
        content: &str,
    ) -> Result<Option<BlobStorageConfiguration>, super::BlobStorageConfigurationError> {
        let document = DocumentMut::from_str(content).expect("the fixture is valid TOML");
        BlobStorageConfiguration::parse(document.get("blob_storage"), 1)
    }

    fn oversized_store_catalog() -> String {
        let mut content = String::from(
            "[blob_storage]\nversion = 1\nstaging_directory = \"/tmp/staging\"\nmax_blob_bytes = 1\n",
        );
        for ordinal in 0..=MAX_BLOB_STORES {
            writeln!(
                content,
                "[[blob_storage.stores]]\nname = \"store-{ordinal}\"\nnamespace_id = \"5a100001-0000-0000-0000-{ordinal:012}\"\nkind = \"filesystem\"\nroot_directory = \"/tmp/store-{ordinal}\""
            )
            .expect("writing to a string cannot fail");
        }
        content.push_str(
            "[blob_storage.routes]\nuser_attachment = \"store-0\"\ntool_artifact = \"store-0\"\nimported_source = \"store-0\"\ngenerated_artifact = \"store-0\"\n",
        );
        content
    }

    fn configuration_fixture() -> BlobStorageConfiguration {
        parse(VALID)
            .expect("the complete catalog is valid")
            .expect("the section is present")
    }

    #[test]
    fn valid_catalog_preserves_the_blob_limit() {
        let configuration = configuration_fixture();

        assert_eq!(configuration.max_blob_bytes(), MAX_BYTES_FIXTURE);
    }

    #[test]
    fn valid_catalog_preserves_the_user_attachment_route() {
        let configuration = configuration_fixture();
        let primary =
            BlobStoreName::try_new(PRIMARY_NAME_FIXTURE).expect("the fixture name is valid");

        assert_eq!(
            configuration.route(BlobStorageClass::UserAttachment).0,
            &primary
        );
    }

    #[test]
    fn valid_catalog_preserves_the_filesystem_root() {
        let configuration = configuration_fixture();
        let primary =
            BlobStoreName::try_new(PRIMARY_NAME_FIXTURE).expect("the fixture name is valid");

        assert_eq!(
            configuration
                .store(&primary)
                .and_then(|store| store.filesystem_root()),
            Some(std::path::Path::new(PRIMARY_ROOT_FIXTURE))
        );
    }

    #[test]
    fn valid_catalog_preserves_the_store_count() {
        let configuration = configuration_fixture();

        assert_eq!(configuration.stores().count(), STORE_COUNT_FIXTURE);
    }

    #[test]
    fn valid_catalog_resolves_a_recorded_store() {
        let configuration = configuration_fixture();
        let primary =
            BlobStoreName::try_new(PRIMARY_NAME_FIXTURE).expect("the fixture name is valid");

        assert!(configuration.resolves_recorded_stores([&primary]));
    }

    #[test]
    fn omitted_catalog_disables_blob_storage() {
        assert_eq!(parse("version = 1").expect("omission is valid"), None);
    }

    #[test]
    fn route_change_moves_new_writes_without_reinterpreting_recorded_stores() {
        let original = parse(VALID)
            .expect("the original catalog is valid")
            .expect("the original section is present");
        let rerouted = parse(&VALID.replace(
            "user_attachment = \"primary\"",
            "user_attachment = \"archive\"",
        ))
        .expect("the rerouted catalog is valid")
        .expect("the rerouted section is present");
        let primary =
            BlobStoreName::try_new(PRIMARY_NAME_FIXTURE).expect("the fixture name is valid");

        assert_ne!(
            original.route(BlobStorageClass::UserAttachment).0,
            rerouted.route(BlobStorageClass::UserAttachment).0
        );
        assert!(rerouted.resolves_recorded_stores([&primary]));
    }

    #[test]
    fn catalog_rejects_more_than_the_named_store_bound() {
        assert!(parse(&oversized_store_catalog()).is_err());
    }

    #[test]
    fn configuration_debug_omits_paths_endpoints_and_bucket_names() {
        let configuration = parse(VALID)
            .expect("the complete catalog is valid")
            .expect("the section is present");

        let debug = format!("{configuration:?}");

        assert!(!debug.contains(PRIMARY_ROOT_FIXTURE));
        assert!(!debug.contains(S3_ENDPOINT_HOST_FIXTURE));
        assert!(!debug.contains(S3_BUCKET_FIXTURE));
    }

    #[test]
    fn catalog_rejects_an_unknown_top_level_field() {
        let unknown = VALID.replace("version = 1", "version = 1\nextra = true");

        assert!(parse(&unknown).is_err());
    }

    #[test]
    fn catalog_rejects_a_field_inapplicable_to_the_store_kind() {
        let inapplicable = VALID.replace(
            "root_directory = \"/var/lib/signalbox/blobs\"",
            "root_directory = \"/var/lib/signalbox/blobs\"\nbucket = \"wrong-kind\"",
        );

        assert!(parse(&inapplicable).is_err());
    }

    #[test]
    fn catalog_rejects_a_duplicate_store_name() {
        let duplicate = VALID.replace("name = \"archive\"", "name = \"primary\"");

        assert!(parse(&duplicate).is_err());
    }

    #[test]
    fn catalog_rejects_a_dangling_route_store_name() {
        let dangling = VALID.replace("tool_artifact = \"archive\"", "tool_artifact = \"missing\"");

        assert!(parse(&dangling).is_err());
    }

    #[test]
    fn catalog_rejects_duplicate_namespace_identities() {
        let duplicate = VALID.replace(
            "5a100001-0000-0000-0000-000000000002",
            "5a100001-0000-0000-0000-000000000001",
        );

        assert!(parse(&duplicate).is_err());
    }

    #[test]
    fn catalog_rejects_an_uppercase_namespace_identity() {
        let uppercase = VALID.replace(
            "5a100001-0000-0000-0000-000000000001",
            "5A100001-0000-0000-0000-000000000001",
        );

        assert!(parse(&uppercase).is_err());
    }

    #[test]
    fn catalog_rejects_a_compact_namespace_identity() {
        let compact = VALID.replace(
            "5a100001-0000-0000-0000-000000000001",
            "5a100001000000000000000000000001",
        );

        assert!(parse(&compact).is_err());
    }

    #[test]
    fn catalog_rejects_a_blob_limit_below_the_import_limit() {
        let document = DocumentMut::from_str(VALID).expect("the fixture is valid TOML");

        let result = BlobStorageConfiguration::parse(document.get("blob_storage"), u64::MAX);

        assert!(result.is_err());
    }

    #[test]
    fn catalog_requires_an_absolute_staging_path() {
        let relative = VALID.replace(
            "staging_directory = \"/var/lib/signalbox/blob-staging\"",
            "staging_directory = \"blob-staging\"",
        );

        assert!(parse(&relative).is_err());
    }

    #[test]
    fn catalog_requires_every_semantic_route() {
        let incomplete = VALID.replace("generated_artifact = \"archive\"", "");

        assert!(parse(&incomplete).is_err());
    }

    #[test]
    fn s3_endpoint_rejects_userinfo() {
        let credential = VALID.replace(
            "https://objects.example.test",
            "https://user:secret@objects.example.test",
        );

        assert!(parse(&credential).is_err());
    }

    #[test]
    fn s3_endpoint_rejects_a_query() {
        let query = VALID.replace(
            "https://objects.example.test",
            "https://objects.example.test?secret=value",
        );

        assert!(parse(&query).is_err());
    }

    #[test]
    fn s3_endpoint_rejects_non_loopback_http() {
        let plain_http = VALID.replace(
            "https://objects.example.test",
            "http://objects.example.test",
        );

        assert!(parse(&plain_http).is_err());
    }

    #[test]
    fn s3_endpoint_admits_literal_loopback_http() {
        let loopback = VALID.replace("https://objects.example.test", "http://127.0.0.1:9000");

        assert!(parse(&loopback).is_ok());
    }
}
