load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")

rust_package()

rust_library(
    name = "signalbox_module_repo_watch_v2",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [],
    crate_features = ["test-support"],
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//crates/ownership-seam:signalbox_ownership_seam"] + all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox_module_repo_watch_v2",
    crate_features = ["test-support"],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)
