//! Bounded staged output awaiting independent validation and artifact publication.

use crate::{
    FileDigest, FileMediaReference, FileReadResult, ReaderIdentity, SourceReadError,
    SourceReadFuture, ValidatedFile, VerifiedBlobSource,
};
use std::num::NonZeroU64;

/// A read either completed directly or produced bytes that still require publication.
#[derive(Debug)]
pub enum PreparedFileRead {
    /// An ordinary bounded result or direct reference.
    Result(FileReadResult),
    /// Bounded generated bytes; no durable reference has been admitted yet.
    Generated(GeneratedMediaView),
}

/// Checked binary envelope whose type and reader claims still require re-detection.
#[derive(Debug)]
pub struct GeneratedMediaView {
    pub(crate) source: ValidatedFile,
    pub(crate) expected_reader: ReaderIdentity,
    pub(crate) media_type: crate::CanonicalMediaType,
    pub(crate) bounds: crate::ReadViewBounds,
    pub(crate) bytes: ArtifactBytes,
}

/// Independently validated staged bytes, publishable before their reference is committed.
#[derive(Debug)]
pub struct ValidatedMediaArtifact {
    pub(crate) reference: FileMediaReference,
    pub(crate) bytes: ArtifactBytes,
}

impl ValidatedMediaArtifact {
    /// Borrows the bounded encoded output; no source bytes are retained here.
    pub fn bytes(&self) -> &[u8] {
        &self.bytes.bytes
    }
    /// Borrows the source and presented evidence authenticated before publication.
    pub const fn reference(&self) -> &FileMediaReference {
        &self.reference
    }
    /// Takes the reference after the caller has published and registered the artifact.
    pub fn into_reference(self) -> FileMediaReference {
        self.reference
    }
}

pub(crate) struct ArtifactBytes {
    pub(crate) bytes: Vec<u8>,
    digest: FileDigest,
    length: NonZeroU64,
}

impl ArtifactBytes {
    pub(crate) fn new(bytes: Vec<u8>) -> Option<Self> {
        use sha2::{Digest as _, Sha256};
        let length = NonZeroU64::new(bytes.len() as u64)?;
        Some(Self {
            digest: FileDigest::from_bytes(Sha256::digest(&bytes).into()),
            bytes,
            length,
        })
    }
}

impl std::fmt::Debug for ArtifactBytes {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ArtifactBytes")
            .field("digest", &self.digest)
            .field("byte_length", &self.length)
            .finish()
    }
}

impl VerifiedBlobSource for ArtifactBytes {
    fn digest(&self) -> FileDigest {
        self.digest
    }
    fn byte_length(&self) -> NonZeroU64 {
        self.length
    }
    fn read_range(&self, offset: u64, length: NonZeroU64) -> SourceReadFuture<'_> {
        Box::pin(async move {
            let end = offset
                .checked_add(length.get())
                .filter(|end| *end <= self.length.get())
                .ok_or(SourceReadError::RangeOutOfBounds)?;
            Ok(self.bytes[offset as usize..end as usize].to_vec())
        })
    }
}
