load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_proc_macro")

rust_package()

rust_proc_macro(
    name = "signalbox_derive",
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox_derive",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_test(
    name = "accessors",
    size = "small",
    srcs = ["tests/accessors.rs"],
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate_features = [],
    crate_root = "tests/accessors.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [":signalbox_derive"] + all_crate_deps(
        proc_macro = True,
        proc_macro_dev = True,
    ),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    tags = [],
    deps = [] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "operator_error",
    size = "small",
    srcs = ["tests/operator_error.rs"],
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate_features = [],
    crate_root = "tests/operator_error.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [":signalbox_derive"] + all_crate_deps(
        proc_macro = True,
        proc_macro_dev = True,
    ),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    tags = [],
    deps = [] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
