load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//cargo:defs.bzl", "cargo_toml_env_vars", "extract_cargo_lints")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(["Cargo.toml"])

cargo_toml_env_vars(
    name = "cargo_environment",
    src = "Cargo.toml",
    workspace = "//:Cargo.toml",
)

extract_cargo_lints(
    name = "cargo_lints",
    manifest = "Cargo.toml",
    workspace = "//:Cargo.toml",
)

rust_library(
    name = "signalbox_model_runtime_openai",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [],
    crate_features = [],
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//crates/model-runtime:signalbox_model_runtime"] + all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox_model_runtime_openai",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

filegroup(
    name = "rust_sources",
    srcs = glob(["**/*.rs"]),
    visibility = ["//:__pkg__"],
)

rust_test(
    name = "loopback",
    size = "small",
    srcs = ["tests/loopback.rs"],
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate_features = [],
    crate_root = "tests/loopback.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(
        proc_macro = True,
        proc_macro_dev = True,
    ),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    tags = [],
    deps = [
        ":signalbox_model_runtime_openai",
        "//crates/model-runtime:signalbox_model_runtime",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
