load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_api_json", "rust_doc_test", "rust_integration_test", "rust_unit_test")

CRATE_FEATURES = [
    "default",
    "test-support",
]

rust_package()

rust_library(
    name = "signalbox_blob_store_filesystem",
    crate_features = CRATE_FEATURES,
    crate_root = "src/lib.rs",
    deps = [
        "//crates/blob-store:signalbox_blob_store",
        "//crates/domain:signalbox_domain",
    ],
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_blob_store_filesystem",
    crate_features = CRATE_FEATURES,
    deps = ["//crates/blob-store:signalbox_blob_store"],
)

rust_integration_test(
    name = "conformance",
    size = "small",
    crate_features = CRATE_FEATURES,
    crate_root = "tests/conformance.rs",
    tags = [
        "external",
        "no-sandbox",
    ],
    deps = [
        ":signalbox_blob_store_filesystem",
        "//crates/blob-store:signalbox_blob_store",
        "//crates/domain:signalbox_domain",
    ],
)

rust_api_json(
    name = "api_json",
    crate = ":signalbox_blob_store_filesystem",
    crate_features = CRATE_FEATURES,
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_blob_store_filesystem",
    crate_features = [
        "default",
        "test-support",
    ],
)
