load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary", "rust_library")

rust_package()

rust_library(
    name = "signalbox_file_media_adapter_video",
    crate_root = "src/lib.rs",
    deps = [
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_binary(
    name = "signalbox-file-media-video-worker",
    crate_root = "src/bin/signalbox-file-media-video-worker.rs",
    deps = [
        ":signalbox_file_media_adapter_video",
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox_file_media_adapter_video",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_test(
    name = "signalbox_file_media_video_worker_unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox-file-media-video-worker",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_test(
    name = "video_adapter",
    size = "small",
    srcs = glob(["tests/**/*.rs"]),
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate_features = [],
    crate_root = "tests/video_adapter.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(
        proc_macro = True,
        proc_macro_dev = True,
    ),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    tags = [],
    deps = [
        ":signalbox_file_media_adapter_video",
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
