// Generated by scripts/generate-plan-contract.py from crates/tools-plan/src/lib.rs.
// Do not edit by hand.

extension SignalboxProcessProtocol {
  public static let maximumPlanTextUnicodeScalars = 4_096
  public static let maximumPlanReadEntries = 100
  public static let maximumPlanDependenciesPerEntry = 32
  public static let maximumPlanHistoryEvents = 100
}
