load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_api_json", "rust_doc_test", "rust_unit_test")

rust_package()

rust_library(
    name = "signalbox_model_provider_runtime",
    crate_root = "src/lib.rs",
    proc_macro_deps = ["//crates/derive:signalbox_derive"],
    deps = [
        "//crates/application:signalbox_application",
        "//crates/domain:signalbox_domain",
        "//crates/model-runtime:signalbox_model_runtime",
    ],
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_model_provider_runtime",
)

rust_api_json(
    name = "api_json",
    crate = ":signalbox_model_provider_runtime",
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_model_provider_runtime",
)
