load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_doc_test", "rust_unit_test")

CRATE_COMPILE_DATA = ["//:config/signalbox-runner.example.toml"]

rust_package()

rust_library(
    name = "signalbox_runner",
    compile_data = CRATE_COMPILE_DATA,
    crate_root = "src/lib.rs",
    deps = ["//crates/runner-wire:signalbox_runner_wire"],
)

rust_binary(
    name = "signalbox-runner",
    compile_data = CRATE_COMPILE_DATA,
    crate_root = "src/main.rs",
    deps = [
        ":signalbox_runner",
        "//crates/runner-wire:signalbox_runner_wire",
    ],
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_runner",
)

rust_unit_test(
    name = "signalbox_runner_unit_tests",
    crate = ":signalbox-runner",
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_runner",
)
