load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_api_json", "rust_doc_test", "rust_integration_test", "rust_unit_test")

CRATE_FEATURES = ["test-worker"]

rust_package()

rust_library(
    name = "signalbox_file_media_processor_runtime",
    crate_features = CRATE_FEATURES,
    crate_root = "src/lib.rs",
    deps = [
        "//crates/file-media-linux-sandbox:signalbox_file_media_linux_sandbox",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_binary(
    name = "signalbox-file-media-synthetic-worker",
    crate_features = CRATE_FEATURES,
    crate_root = "src/bin/signalbox-file-media-synthetic-worker.rs",
    deps = [
        ":signalbox_file_media_processor_runtime",
        "//crates/file-media-linux-sandbox:signalbox_file_media_linux_sandbox",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
    ],
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_file_media_processor_runtime",
    crate_features = CRATE_FEATURES,
)

rust_unit_test(
    name = "signalbox_file_media_synthetic_worker_unit_tests",
    crate = ":signalbox-file-media-synthetic-worker",
    crate_features = CRATE_FEATURES,
)

rust_api_json(
    name = "api_json",
    crate = ":signalbox_file_media_processor_runtime",
    crate_features = CRATE_FEATURES,
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_file_media_processor_runtime",
    crate_features = ["test-worker"],
)

rust_integration_test(
    name = "isolation",
    srcs = glob(["tests/**/*.rs"]),
    args = [
        "--ignored",
        "--test-threads=4",
    ],
    crate_features = ["test-worker"],
    crate_root = "tests/isolation.rs",
    data = glob(
        ["tests/**"],
        allow_empty = True,
        exclude = ["tests/**/*.rs"],
    ) + [":signalbox-file-media-synthetic-worker"],
    env = {
        "CI": "true",
        "NEXTEST_BIN_EXE_signalbox_file_media_synthetic_worker": "$(rootpath :signalbox-file-media-synthetic-worker)",
    },
    env_inherit = ["SIGNALBOX_FILE_MEDIA_CGROUP_ROOT"],
    rustc_env = {
        "CARGO_MANIFEST_DIR": "crates/file-media-processor-runtime",
        "CARGO_BIN_EXE_signalbox-file-media-synthetic-worker": "$(rootpath :signalbox-file-media-synthetic-worker)",
    },
    tags = [
        "external",
        "manual",
        "no-sandbox",
    ],
    deps = [
        "//crates/file-media-linux-sandbox:signalbox_file_media_linux_sandbox",
        "//crates/file-media-processor-runtime:signalbox_file_media_processor_runtime",
        "//crates/file-media-runtime:signalbox_file_media_runtime",
        "//crates/test-bin:signalbox_test_bin",
    ],
)
