#!/usr/bin/env python3
"""Generate native plan limits from the Rust plan-tool contract."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

NATIVE_ROOT = Path(__file__).resolve().parents[1]
REPOSITORY_ROOT = NATIVE_ROOT.parents[1]
SOURCE = REPOSITORY_ROOT / "crates/tools-plan/src/lib.rs"
OUTPUT = NATIVE_ROOT / "Sources/SignalboxModels/GeneratedPlanContract.swift"

CONSTANTS = (
    ("MAX_PLAN_TEXT_CHARS", "maximumPlanTextUnicodeScalars"),
    ("MAX_PLAN_READ_ENTRIES", "maximumPlanReadEntries"),
    ("MAX_PLAN_DEPENDENCIES_PER_ENTRY", "maximumPlanDependenciesPerEntry"),
    ("MAX_PLAN_HISTORY_EVENTS", "maximumPlanHistoryEvents"),
)


def read_limits(source: str) -> dict[str, int]:
    limits: dict[str, int] = {}
    for rust_name, _ in CONSTANTS:
        matches = re.findall(
            rf"^pub const {rust_name}: usize = ([0-9][0-9_]*);$",
            source,
            flags=re.MULTILINE,
        )
        if len(matches) != 1:
            raise ValueError(f"expected exactly one literal definition of {rust_name}")
        limits[rust_name] = int(matches[0].replace("_", ""))
    return limits


def render(limits: dict[str, int]) -> str:
    declarations = "\n".join(
        f"  public static let {swift_name} = {limits[rust_name]:_}"
        for rust_name, swift_name in CONSTANTS
    )
    return (
        "// Generated by scripts/generate-plan-contract.py from "
        "crates/tools-plan/src/lib.rs.\n"
        "// Do not edit by hand.\n\n"
        "extension SignalboxProcessProtocol {\n"
        f"{declarations}\n"
        "}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    try:
        generated = render(read_limits(SOURCE.read_text(encoding="utf-8")))
    except (OSError, ValueError) as error:
        print(f"plan-contract generation failed: {error}", file=sys.stderr)
        return 1

    if args.write:
        OUTPUT.write_text(generated, encoding="utf-8")
        print(f"wrote {OUTPUT.relative_to(REPOSITORY_ROOT)}")
        return 0

    try:
        current = OUTPUT.read_text(encoding="utf-8")
    except OSError as error:
        print(f"plan-contract check failed: {error}", file=sys.stderr)
        return 1
    if current == generated:
        print("native plan contract is current")
        return 0
    print(
        "".join(
            difflib.unified_diff(
                current.splitlines(keepends=True),
                generated.splitlines(keepends=True),
                fromfile=str(OUTPUT.relative_to(REPOSITORY_ROOT)),
                tofile="generated plan contract",
            )
        ),
        file=sys.stderr,
    )
    print(
        "native plan contract is stale; run "
        "clients/native/scripts/generate-plan-contract.py --write",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
