#!/usr/bin/env python3
"""Check that stated invariant/scenario counts match their generated catalogs.

Two catalogs in this repository are generative ground truth, not free prose.
`docs/invariants.md` is entirely regenerated by
`scripts/generate_invariants.py` from INV-tagged Rust tests — one row per
distinct tag, and `--check` fails the documentation validation bar whenever
the committed file drifts from that derivation. `docs/scenarios.md` names
each design scenario under its own `## S<N> — <title>` heading; AGENTS.md and
the testing-style rules point tests at those identifiers directly. Neither
catalog states its own size in prose, so both are counted mechanically here
rather than estimated: the invariant count is the number of distinct
`| INV-NNN |` rows in `docs/invariants.md`, and the scenario count is the
number of distinct `## S<N>` headings in `docs/scenarios.md`.

Prose elsewhere occasionally restates one of those totals ("the catalog
defines 50 invariants", "scenario count: 37", "count of scenarios: 38")
instead of pointing at the catalog. That restatement goes stale the moment a
scenario or invariant is added or removed without also touching the sentence
that quoted the old total — the same staleness class `check_domain_spine.py`
guards against for the domain crates' exported-type counts. This script scans
every tracked Markdown file for a stated count next to the word "invariant" or
"scenario" and fails when it disagrees with the catalog — every file except the
non-authoritative planning scratchpads, which AGENTS.md exempts from
consistency review and whose quantities decide nothing.

The scan reads each document whole, not line by line, so a statement the
required mdformat pass wrapped between its number and its noun still reads as
one statement, and it reads what the document *renders*: inline emphasis and
link delimiters between the number and the noun are stepped over, because
"There are **51** invariants" states the same total as the unformatted
sentence. Literal content is excluded first, through the masking helpers in
`check_docs_consistency` — fences (including `~~~`, long, and container-nested
ones), indented code, HTML comments, raw HTML blocks, and inline code spans.
The same block masking is applied to the two catalogs themselves, so an
example row or heading — fenced, or drafted inside an HTML comment — cannot
inflate ground truth.

This mechanizes check class (2), "stale-count checks", of the
invariant-citation review work commissioned for this checker. The other two
classes already have deterministic coverage elsewhere and are deliberately
NOT reimplemented here:

* citation EXISTENCE — every INV-NNN cited in code comments or docs prose
  resolves to a real, test-backed `docs/invariants.md` row — is enforced by
  `orphan_invariant_references()` in `scripts/generate_invariants.py` (run
  through its `--check` mode) together with `check_invariant_citations()` in
  `scripts/check_docs_consistency.py`, which cross-checks every Enforcement
  cell against the tagged Rust tests in both directions: an orphaned citation
  with no tagged test fails the former, and a tagged test the catalog fails
  to cite fails the latter.
* internal LINK resolution, including links between the invariant index and
  spec pages, is enforced by `check_relative_links()` in
  `scripts/check_docs_consistency.py`, which resolves every relative
  Markdown link (and GitHub-style heading fragment) under `docs/**/*.md` and
  `AGENTS.md` — a strict superset of "invariant index <-> spec page" links,
  since `docs/invariants.md` and `docs/spec/*.md` are both inside `docs/`.

Known limitation, and the scope this checker is written to: the count-statement
scan is a heuristic over Markdown source, not a CommonMark renderer, and it is
best-effort by design in both directions.

It can miss a stale count wearing a Markdown shape the patterns do not model —
emphasis nested around a link around the number, a construct split across a
container prefix, an inline HTML element — and it can read a count out of
source that renders as nothing, if that source is a form the masking helpers do
not cover. Both are accepted costs, not oversights. The value here is catching
the ordinary restatement, which is how a stale total actually gets written; the
alternative is a full renderer, which is a dependency and a parser this
repository has deliberately not taken on for a report-only staleness check.

So a newly-discovered shape is not automatically a defect to fix. Widen the
patterns or the masking when a shape is one this repository's documentation
actually writes; leave it when the shape is only reachable in principle. What
must stay true is that no *supported* shape reports a wrong number: a
miscounted total that agrees with the catalog is the only failure this file
treats as unconditional, because nothing downstream would ever surface it.

A coincidental "<number> invariants"/"<number> scenarios" adjacency that is not
stating a total would also false-positive (e.g. "5 invariants changed in the
last 2 scenarios" reads as a claim of 5 total invariants). None exists in the
tree today; broaden `NUMBER_BEFORE_NOUN` / `NOUN_COUNT_PHRASE`, or add a
reviewed exclusion, if one legitimately arises.

Standalone invocation — this script is not part of
`.github/workflows/rust.yml` or the AGENTS.md documentation bar, so nothing
runs it automatically. Run it directly:

    python3 scripts/check_invariant_scenario_counts.py

Run from the repository root; exits nonzero with a per-statement report on
any mismatch.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from check_docs_consistency import (
    REFERENCE_DEFINITION,
    is_escaped,
    mask_block_content,
    mask_inline_code,
    mask_range,
    parse_inline_link_at,
)
from generate_invariants import has_non_authoritative_planning_banner

INVARIANTS = Path("docs/invariants.md")
SCENARIOS = Path("docs/scenarios.md")

INVARIANT_ROW = re.compile(r"^\|\s*(INV-[0-9]{3})\s*\|", re.MULTILINE)
SCENARIO_HEADING = re.compile(r"^##\s+(S[0-9]+)\b", re.MULTILINE)

# The whitespace between the words of one statement, which may fall across a
# wrapped line: prose here is hard-wrapped and the required mdformat pass
# rewraps it, so "the catalog defines 50\ninvariants" is a single claim and has
# to read as one. At most one newline — a blank line ends the paragraph, and a
# number in one paragraph states nothing about a noun in the next — and a
# block-quote marker may lead the continuation, the way `CARRIER_GAP` in
# `check_docs_consistency.py` already allows for its own wrapped carriers.
# Repeated markers are accepted, not just one: a statement nested two levels
# deep wraps as "> > There are 51\n> > invariants", and stopping at a single
# `>` would let exactly the stale counts inside quoted material through.
#
# Inline markup may sit on either side of that whitespace. "There are **51**
# invariants", "51 **invariants**" and "51 [invariants](invariants.md)" all
# render as the same sentence, so the emphasis and link delimiters must not be
# what decides whether a stale total is caught. Only the delimiters are
# skipped, never the words between them, so "51 and 3 invariants" still reads
# as two separate tokens rather than one span.
#
# A link around either token is markup as well: "There are
# [51](invariants.md) invariants" links the number. Inline destinations are
# already blanked by `mask_link_metadata`, so only the reference form needs
# spelling out here; its body excludes the closing delimiter and newlines, so
# the repetition is anchored and cannot run away across a document.
MARKUP_CONSTRUCT = re.compile(r"\]\[[^\]\n]*\]|[*_~`\[\]]")
MARKUP = rf"(?:{MARKUP_CONSTRUCT.pattern})*"
WRAPPED_GAP = rf"(?:{MARKUP}(?:[ \t]+|[ \t]*\r?\n[ \t]*(?:>[ \t]*)*){MARKUP})"

# A digit run that is only part of a larger number: "37.5" and "1,000" must not
# read as 37 and 1. Rejecting is the safe direction — a total this cannot parse
# is skipped rather than misreported as a different number.
NOT_PARTIAL_NUMBER = r"(?![0-9])(?![.,][0-9])"

# The whitespace a range terminus may be separated from either of its bounds
# by, including the hard wrap the required mdformat pass can leave between them
# and the block-quote markers such a wrap carries. At most one newline, for the
# same reason `WRAPPED_GAP` stops there: a blank line ends the paragraph, and a
# number in one paragraph bounds nothing in the next.
RANGE_GAP = r"[ \t]*(?:\r?\n[ \t]*(?:>[ \t]*)*)?[ \t]*"

# A number that is only one bound of a range states no total, so the text on
# both sides of a candidate is examined. `and` is deliberately absent from both
# patterns, being ordinary conjunction far more often than a range terminus:
# "3 sessions and 37 scenarios" states a real total.
#
# Both are applied by searching the text around a candidate match rather than as
# lookarounds, because Python lookbehinds must be fixed width and these are not:
# "5 to 37", "5 to\n37", "5 – 37" and "5\u201337" are the same statement.
#
# A terminus immediately *before* the number makes it the upper bound, and each
# such number reports a total that can agree with the catalog and pass in
# silence. The dashes live here rather than in the boundary class below for the
# same reason; that is also what refuses `INV-002`, since `INV-` ends in one.
RANGE_PREFIX = re.compile(
    rf"(?:\bto|\bthrough|\bthru|[-\u2010-\u2015]){RANGE_GAP}$",
    re.IGNORECASE,
)

# A terminus immediately *after* the number makes it the lower bound. Only the
# noun-count phrases below reach this shape — nothing separates
# "scenario count: 37" from "scenario count: 37\u201350", so a range written
# against the catalog's own size was read as a stated total and passed — while
# `NUMBER_BEFORE_NOUN` cannot, its noun standing where a terminus would.
#
# An upper bound is required rather than assumed, so prose that merely ends in a
# dash still leaves its count readable.
#
# Anchored by `re.match` at the number's end rather than by `^`, which asserts
# a line start and would refuse every terminus that does not follow a newline.
RANGE_SUFFIX = re.compile(
    rf"{RANGE_GAP}(?P<terminus>to\b|through\b|thru\b|[-\u2010-\u2015])"
    rf"{RANGE_GAP}[0-9]",
    re.IGNORECASE,
)

# What may precede a list bullet on its own line: indentation, and the
# block-quote markers of whatever depth the bullet is nested inside.
LIST_BULLET_LEAD = re.compile(r"[ \t]*(?:>[ \t]*)*")

# A number sitting directly before the noun: "50 invariants", "1 scenario".
# The lookbehind refuses a digit run glued to a preceding word, decimal point,
# or hyphen; the lookahead refuses one glued to a following word or hyphen (so
# `50-invariant` doesn't qualify).
#
# The hyphen in the lookbehind is what keeps a citation from reading as a
# total: "the INV-002 invariant" would otherwise match at `002` and claim the
# catalog states 2. Since AGENTS.md requires those citations, without this the
# checker fails on the very references it exists to protect. The cost is that a
# range written "5-10 scenarios" no longer matches, which is correct — a range
# states no total.
#
# A range can also be written in words, and "5 to 37 scenarios" would otherwise
# match at `37` — again *agreeing* with a 37-scenario catalog and passing in
# silence. Only unambiguous range termini are excluded: `and` is not one, since
# "3 sessions and 37 scenarios" states a real total.
#
# The Unicode dashes U+2010-U+2015 join the ASCII hyphen for the same reason.
# This repository writes ranges with an en dash — "1-64 ASCII letters" in
# docs/spec/tool-loop.md is really "1\u201364" — so "5\u201337 scenarios" would start
# matching after the dash and report 37, which *agrees* with a 37-scenario
# catalog and passes silently. A range states no total, whichever dash it uses.
#
# `,` joins them for the mirror-image reason `NOT_PARTIAL_NUMBER` exists: without
# it the engine simply restarts after the comma, so "There are 12,037 scenarios"
# matches at `037` and reads as 37 — which *agrees* with a 37-scenario catalog
# and passes silently. Guarding only the characters after the capture left the
# same defect on the other side of it.
#
# `_` is deliberately absent from both classes, unlike `\w`: it is Markdown's
# other emphasis delimiter, and refusing it would let "There are _51_
# invariants" hide a stale total exactly as `**51**` did. The exposure is a
# snake_case identifier written as bare prose, which this repository formats as
# inline code — masked above before any of these patterns run.
NUMBER_BEFORE_NOUN = re.compile(
    rf"(?<![0-9A-Za-z.,])"
    rf"(?P<number>[0-9]{{1,4}}){NOT_PARTIAL_NUMBER}{WRAPPED_GAP}"
    rf"(?P<noun>invariants?|scenarios?)(?![0-9A-Za-z-])",
    re.IGNORECASE,
)
# The noun stated as an explicit count: "invariant count: 50", "scenario
# count is 37". The connector before the digits is optional so bare
# "invariant count 50" still matches. Either word may carry markup —
# "scenario **count**: 9" and "count of **scenarios**: 9" both put a closing
# delimiter directly before the punctuation, where no whitespace follows for
# the gap to absorb it.
NOUN_COUNT_PHRASE = re.compile(
    rf"\b(?P<noun>invariant|scenario)s?{MARKUP}{WRAPPED_GAP}count{MARKUP}{WRAPPED_GAP}?"
    rf"(?:is|of|:|=)?{WRAPPED_GAP}?(?P<number>[0-9]{{1,4}}){NOT_PARTIAL_NUMBER}",
    re.IGNORECASE,
)
# The same claim with the words the other way round: "count of scenarios: 38",
# "the count of invariants is 51". Neither existing pattern reaches this — the
# noun follows `count` rather than leading it, and the number is too far from
# the noun for `NUMBER_BEFORE_NOUN` to bridge.
COUNT_OF_NOUN_PHRASE = re.compile(
    rf"\bcount{MARKUP}{WRAPPED_GAP}of{WRAPPED_GAP}(?P<noun>invariant|scenario)s?{MARKUP}"
    rf"{WRAPPED_GAP}?(?:is|of|:|=)?{WRAPPED_GAP}?(?P<number>[0-9]{{1,4}}){NOT_PARTIAL_NUMBER}",
    re.IGNORECASE,
)


class CountCheckError(RuntimeError):
    """Ground truth (a catalog or the tracked-file inventory) is unusable."""


def tracked_markdown_files() -> list[Path]:
    """Return every tracked Markdown file, via Git's own inventory.

    A plain directory walk from the repository root would also read Markdown
    left in a sibling `.claude/worktrees/` checkout of this same repository.
    Git's tracked-file list is scoped to this branch's index and excludes an
    untracked sibling worktree entirely — the same discipline
    `scripts/check_docs_consistency.py` documents and tests for its own
    Markdown discovery.
    """
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", "*.md"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or "git ls-files failed"
        raise CountCheckError(f"tracked-file discovery failed: {detail}")
    labels = [label for label in result.stdout.split("\0") if label]
    if not labels:
        raise CountCheckError("git ls-files returned no Markdown files")
    return [Path(label) for label in labels]


def distinct_identifiers(found: list[str], source: Path, kind: str) -> set[str]:
    """Return the identifiers, refusing to define a catalog size by collapsing.

    `set()` on its own turns a duplicated identifier into a silent no-op: a
    scenario section copied without renaming its heading would leave the
    catalog one section larger while the reported total stayed put, so every
    accurate stated count would still pass and the ambiguity would never
    surface. A duplicate is a defect in the catalog, and the size is not
    answerable until it is fixed.
    """
    duplicates = sorted({tag for tag in found if found.count(tag) > 1})
    if duplicates:
        raise CountCheckError(
            f"{source} declares {kind} more than once: {', '.join(duplicates)}"
        )
    return set(found)


def actual_invariant_count() -> int:
    """Return the number of distinct rows in the generated invariant index.

    Literal content is masked first, on the same grounds as `find_stated_counts`
    below, and through the same `mask_block_content`: a documented example of
    the row format is a sample, and a row inside an HTML comment is a draft.
    Counting either would inflate ground truth itself and so fail every
    accurate stated count in the tree — the loudest possible failure mode.
    """
    text = mask_block_content(INVARIANTS.read_text(encoding="utf-8"))
    tags = distinct_identifiers(INVARIANT_ROW.findall(text), INVARIANTS, "an invariant")
    if not tags:
        raise CountCheckError(f"{INVARIANTS} has no parseable INV-NNN rows")
    return len(tags)


def actual_scenario_count() -> int:
    """Return the number of distinct `## S<N>` scenario headings.

    Literal content is masked for the same reason as in
    `actual_invariant_count`: a `## S99 — Example` inside a fence or an HTML
    comment renders as code or not at all, names no scenario, and must not
    enlarge the catalog it is only illustrating.

    A repeated identifier is an error rather than a duplicate to collapse; see
    `distinct_identifiers`.
    """
    text = mask_block_content(SCENARIOS.read_text(encoding="utf-8"))
    tags = distinct_identifiers(SCENARIO_HEADING.findall(text), SCENARIOS, "a scenario")
    if not tags:
        raise CountCheckError(f"{SCENARIOS} has no parseable scenario headings")
    return len(tags)


def mask_link_metadata(text: str) -> str:
    r"""Blank what a link contributes to source but not to rendered prose.

    A destination and title are not read by anyone reading the document, so a
    catalog path or a title like `"5 invariants"` must not be scanned as a
    claim — and a reference definition line renders as nothing at all. The
    label is kept, because it *is* rendered: "There are [51](catalog.md)
    invariants" states a total, and blanking the whole construct would delete
    the number the sentence depends on.

    Masking the destination rather than teaching the gap to cross it is also
    what keeps this file out of the link-grammar business. `parse_inline_link_at`
    already handles balanced parentheses, angle-bracketed destinations, and
    titles; duplicating a subset of that in a regex is how the earlier
    `[^()\s]*` destination came to reject `catalog_(current).md`.

    Offsets and line breaks are preserved, so reported line numbers still hold.
    """
    buffer = list(text)
    index = 0
    while index < len(text):
        if text[index] != "[" or is_escaped(text, index):
            index += 1
            continue
        parsed = parse_inline_link_at(text, index)
        if parsed is None:
            index += 1
            continue
        link, closing = parsed
        # From the label's closing bracket through the destination's `)`.
        mask_range(buffer, index + 1 + len(link.label), closing + 1)
        index = closing + 1
    masked = "".join(buffer)
    # Reference definitions render as nothing, so the whole declaration goes.
    buffer = list(masked)
    for match in REFERENCE_DEFINITION.finditer(masked):
        mask_range(buffer, match.start(), match.end())
    return "".join(buffer)


def line_number_at(text: str, offset: int) -> int:
    """Return the 1-based line the offset falls on."""
    return text.count("\n", 0, offset) + 1


def as_one_phrase(matched: str) -> str:
    """Collapse a match that spans a wrapped line into one reportable phrase.

    Quote markers the wrap carried, and the inline markup the patterns now step
    over, are dropped: a claim written "There are **51**\ninvariants" inside a
    nested quote reports as "51 invariants", and a reference-linked number
    reports as "51 invariants" rather than "51][index invariants". The same
    constructs the gap steps over are the ones removed here, so the two cannot
    drift; every word the document actually states is still quoted back.
    """
    without_markup = MARKUP_CONSTRUCT.sub(" ", matched)
    return " ".join(word for word in without_markup.split() if set(word) != {">"})


def opens_a_list_item(text: str, offset: int) -> bool:
    """Whether the character at `offset` is a bullet marker, not a range dash.

    A hyphen that opens a Markdown list item is the one range terminus this
    repository's prose writes for a different purpose entirely: "- 9 scenarios
    are catalogued" is a bullet stating a total, not the tail of a range, and
    reading it as one discarded the count and let a stale total pass — while the
    same sentence as a paragraph, or under a `+` or `*` bullet, failed as it
    should. `+` and `*` are not range termini, so only `-` is ambiguous, and only
    the ASCII hyphen: CommonMark's bullets are exactly `-`, `+` and `*`, so a
    line opening with U+2010-U+2015 is prose whichever dash it uses.

    A bullet is a marker with nothing but indentation and block-quote markers
    before it on its line, and whitespace after it — `-9` is a negative number,
    not an empty list item, so the count it bounds stays refused.
    """
    if text[offset] != "-":
        return False
    if offset + 1 >= len(text) or text[offset + 1] not in " \t\r\n":
        return False
    line_start = text.rfind("\n", 0, offset) + 1
    return LIST_BULLET_LEAD.fullmatch(text[line_start:offset]) is not None


def bounds_a_range(text: str, match: re.Match[str]) -> bool:
    """Whether the captured number is one bound of a range rather than a total.

    Both sides are asked, because a range states no total from either end: the
    upper bound of "5 to 37 scenarios" and the lower bound of "scenario count:
    37-50" each report 37, which *agrees* with a 37-scenario catalog and so
    passes in silence — the one failure mode nothing downstream would surface.

    A terminus that turns out to be a list bullet is not a range on either side.
    Testing that here rather than inside the patterns keeps the ambiguity in one
    place, so the two directions cannot disagree about what a dash means.
    """
    before = RANGE_PREFIX.search(text[: match.start("number")])
    if before is not None and not opens_a_list_item(text, before.start()):
        return True
    after = RANGE_SUFFIX.match(text, match.end("number"))
    return after is not None and not opens_a_list_item(text, after.start("terminus"))


def find_stated_counts(path: Path) -> list[tuple[int, str, int, str]]:
    """Return (line, noun, stated count, matched text) for one Markdown file.

    The whole document is scanned at once rather than line by line, because a
    statement wrapped between its number and its noun is still that statement.
    Every form of literal content is masked first, not just fenced blocks:
    `mask_block_content` covers fences, HTML comments, raw HTML blocks and
    indented code, and `mask_inline_code` covers backtick spans. All of them
    blank in place — same length, same line breaks — so offsets still name the
    right line, and they are reused rather than re-approximated: they already
    handle `~~~` fences, fences longer than three characters, and fences nested
    in block quotes and list items, none of which an opening-delimiter toggle
    gets right. A code example, a commented-out draft, or an inline
    `50 invariants` is not a claim about the catalog.

    A file opening with the non-authoritative-planning banner states nothing at
    all and yields no counts. AGENTS.md exempts those scratchpads from
    consistency review and lets them be revised freely, so a backlog item
    reading "5 scenarios" is a work quantity, not a claim about the catalog.
    The banner test is imported from `generate_invariants.py`, which already
    applies it when validating invariant references, so both checks exempt
    exactly the same set of files.
    """
    raw = path.read_text(encoding="utf-8", errors="replace")
    if has_non_authoritative_planning_banner(raw):
        return []
    text = mask_link_metadata(mask_inline_code(mask_block_content(raw)))
    found: list[tuple[int, str, int, str]] = []
    # Every pattern names its two captures `noun` and `number`, so the three
    # can be read the same way regardless of which order the words fall in.
    for pattern in (NUMBER_BEFORE_NOUN, NOUN_COUNT_PHRASE, COUNT_OF_NOUN_PHRASE):
        for match in pattern.finditer(text):
            # A number that bounds a range states no total, from either end and
            # however the range was spelled or wrapped.
            if bounds_a_range(text, match):
                continue
            noun = (
                "invariant"
                if match.group("noun").lower().startswith("invariant")
                else "scenario"
            )
            found.append(
                (
                    line_number_at(text, match.start()),
                    noun,
                    int(match.group("number")),
                    as_one_phrase(match.group(0)),
                )
            )
    return found


def main() -> int:
    try:
        actual = {
            "invariant": actual_invariant_count(),
            "scenario": actual_scenario_count(),
        }
        files = tracked_markdown_files()
    except (CountCheckError, OSError) as error:
        print(f"invariant/scenario count check FAILED: {error}")
        return 1

    failures: list[str] = []
    for path in files:
        # A tracked path can be unreadable while the index still lists it —
        # an unstaged deletion during local validation is the ordinary way.
        # That is reported as a failure like any other rather than raised: a
        # traceback would replace the whole report, including the findings
        # from every file that read fine.
        try:
            stated_counts = find_stated_counts(path)
        except OSError as error:
            failures.append(
                f"{path.as_posix()}: tracked but could not be read "
                f"({error.__class__.__name__})"
            )
            continue
        for line_number, noun, stated, matched in stated_counts:
            if stated != actual[noun]:
                failures.append(
                    f'{path.as_posix()}:{line_number}: states "{matched}", but '
                    f"the current {noun} catalog has {actual[noun]}"
                )

    if failures:
        print("invariant/scenario count check FAILED — a stated count is stale:")
        for failure in sorted(failures):
            print(f"  - {failure}")
        print(
            "Update the stated count, or reword to point at the catalog instead "
            "of restating it: docs/invariants.md is generated by "
            "scripts/generate_invariants.py --write; docs/scenarios.md scenarios "
            "are counted by their own `## S<N>` headings."
        )
        return 1
    print(
        "invariant/scenario count check passed "
        f"({actual['invariant']} invariants, {actual['scenario']} scenarios)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
