#!/usr/bin/env python3
"""Check that stated invariant/scenario counts match their generated catalogs.

Two catalogs in this repository are generative ground truth, not free prose.
`docs/invariants.md` is entirely regenerated by
`scripts/generate_invariants.py` from INV-tagged Rust tests — one row per
distinct tag, and `--check` fails the documentation validation bar whenever
the committed file drifts from that derivation. `docs/scenarios.md` names
each design scenario under its own `## S<N> — <title>` heading; AGENTS.md and
the testing-style rules point tests at those identifiers directly. Neither
catalog states its own size in prose, so both are counted mechanically here
rather than estimated: the invariant count is the number of distinct
`| INV-NNN |` rows in `docs/invariants.md`, and the scenario count is the
number of distinct `## S<N>` headings in `docs/scenarios.md`.

Prose elsewhere occasionally restates one of those totals ("the catalog
defines 50 invariants", "scenario count: 37", "count of scenarios: 38")
instead of pointing at the catalog. That restatement goes stale the moment a
scenario or invariant is added or removed without also touching the sentence
that quoted the old total — the same staleness class `check_domain_spine.py`
guards against for the domain crates' exported-type counts. This script scans
every tracked Markdown file for a stated count next to the word "invariant" or
"scenario" and fails when it disagrees with the catalog — every file except the
non-authoritative planning scratchpads, which AGENTS.md exempts from
consistency review and whose quantities decide nothing.

The scan reads each document whole, not line by line, so a statement the
required mdformat pass wrapped between its number and its noun still reads as
one statement, and it reads what the document *renders*: inline emphasis and
link delimiters between the number and the noun are stepped over, because
"There are **51** invariants" states the same total as the unformatted
sentence. Literal content is excluded first, through the masking helpers in
`check_docs_consistency` — fences (including `~~~`, long, and container-nested
ones), indented code, HTML comments, raw HTML blocks, and inline code spans.
The same block masking is applied to the two catalogs themselves, so an
example row or heading — fenced, or drafted inside an HTML comment — cannot
inflate ground truth.

This mechanizes check class (2), "stale-count checks", of the
invariant-citation review work commissioned for this checker. The other two
classes already have deterministic coverage elsewhere and are deliberately
NOT reimplemented here:

* citation EXISTENCE — every INV-NNN cited in code comments or docs prose
  resolves to a real, test-backed `docs/invariants.md` row — is enforced by
  `orphan_invariant_references()` in `scripts/generate_invariants.py` (run
  through its `--check` mode) together with `check_invariant_citations()` in
  `scripts/check_docs_consistency.py`, which cross-checks every Enforcement
  cell against the tagged Rust tests in both directions: an orphaned citation
  with no tagged test fails the former, and a tagged test the catalog fails
  to cite fails the latter.
* internal LINK resolution, including links between the invariant index and
  spec pages, is enforced by `check_relative_links()` in
  `scripts/check_docs_consistency.py`, which resolves every relative
  Markdown link (and GitHub-style heading fragment) under `docs/**/*.md` and
  `AGENTS.md` — a strict superset of "invariant index <-> spec page" links,
  since `docs/invariants.md` and `docs/spec/*.md` are both inside `docs/`.

Known limitation: the count-statement scan is a heuristic prose pattern, not
a parser — a coincidental "<number> invariants"/"<number> scenarios"
adjacency that is not actually stating a total would false-positive (e.g. "5
invariants changed in the last 2 scenarios" reads as a claim of 5 total
invariants). None exists in the tree today; broaden `NUMBER_BEFORE_NOUN` /
`NOUN_COUNT_PHRASE`, or add a reviewed exclusion, if one legitimately arises.

Standalone invocation — this script is not part of
`.github/workflows/rust.yml` or the AGENTS.md documentation bar, so nothing
runs it automatically. Run it directly:

    python3 scripts/check_invariant_scenario_counts.py

Run from the repository root; exits nonzero with a per-statement report on
any mismatch.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

from check_docs_consistency import mask_block_content, mask_inline_code
from generate_invariants import has_non_authoritative_planning_banner

INVARIANTS = Path("docs/invariants.md")
SCENARIOS = Path("docs/scenarios.md")

INVARIANT_ROW = re.compile(r"^\|\s*(INV-[0-9]{3})\s*\|", re.MULTILINE)
SCENARIO_HEADING = re.compile(r"^##\s+(S[0-9]+)\b", re.MULTILINE)

# The whitespace between the words of one statement, which may fall across a
# wrapped line: prose here is hard-wrapped and the required mdformat pass
# rewraps it, so "the catalog defines 50\ninvariants" is a single claim and has
# to read as one. At most one newline — a blank line ends the paragraph, and a
# number in one paragraph states nothing about a noun in the next — and a
# block-quote marker may lead the continuation, the way `CARRIER_GAP` in
# `check_docs_consistency.py` already allows for its own wrapped carriers.
# Repeated markers are accepted, not just one: a statement nested two levels
# deep wraps as "> > There are 51\n> > invariants", and stopping at a single
# `>` would let exactly the stale counts inside quoted material through.
#
# Inline markup may sit on either side of that whitespace. "There are **51**
# invariants", "51 **invariants**" and "51 [invariants](invariants.md)" all
# render as the same sentence, so the emphasis and link delimiters must not be
# what decides whether a stale total is caught. Only the delimiters are
# skipped, never the words between them, so "51 and 3 invariants" still reads
# as two separate tokens rather than one span.
#
# A complete link around either token is markup as well: "There are
# [51](invariants.md) invariants" links the number, so the gap has to cross the
# entire destination rather than a lone bracket. Inline and reference forms
# both. Each alternative starts with a two-character literal and its body
# excludes the closing delimiter and newlines, so the repetition is anchored
# and cannot run away across a document.
MARKUP_CONSTRUCT = re.compile(r"\]\([^()\s]*\)|\]\[[^\]\n]*\]|[*_~`\[\]]")
MARKUP = rf"(?:{MARKUP_CONSTRUCT.pattern})*"
WRAPPED_GAP = rf"(?:{MARKUP}(?:[ \t]+|[ \t]*\r?\n[ \t]*(?:>[ \t]*)*){MARKUP})"

# A digit run that is only part of a larger number: "37.5" and "1,000" must not
# read as 37 and 1. Rejecting is the safe direction — a total this cannot parse
# is skipped rather than misreported as a different number.
NOT_PARTIAL_NUMBER = r"(?![0-9])(?![.,][0-9])"

# A number sitting directly before the noun: "50 invariants", "1 scenario".
# The lookbehind refuses a digit run glued to a preceding word, decimal point,
# or hyphen; the lookahead refuses one glued to a following word or hyphen (so
# `50-invariant` doesn't qualify).
#
# The hyphen in the lookbehind is what keeps a citation from reading as a
# total: "the INV-002 invariant" would otherwise match at `002` and claim the
# catalog states 2. Since AGENTS.md requires those citations, without this the
# checker fails on the very references it exists to protect. The cost is that a
# range written "5-10 scenarios" no longer matches, which is correct — a range
# states no total.
#
# `,` joins them for the mirror-image reason `NOT_PARTIAL_NUMBER` exists: without
# it the engine simply restarts after the comma, so "There are 12,037 scenarios"
# matches at `037` and reads as 37 — which *agrees* with a 37-scenario catalog
# and passes silently. Guarding only the characters after the capture left the
# same defect on the other side of it.
#
# `_` is deliberately absent from both classes, unlike `\w`: it is Markdown's
# other emphasis delimiter, and refusing it would let "There are _51_
# invariants" hide a stale total exactly as `**51**` did. The exposure is a
# snake_case identifier written as bare prose, which this repository formats as
# inline code — masked above before any of these patterns run.
NUMBER_BEFORE_NOUN = re.compile(
    rf"(?<![0-9A-Za-z.,-])(?P<number>[0-9]{{1,4}}){NOT_PARTIAL_NUMBER}{WRAPPED_GAP}"
    rf"(?P<noun>invariants?|scenarios?)(?![0-9A-Za-z-])",
    re.IGNORECASE,
)
# The noun stated as an explicit count: "invariant count: 50", "scenario
# count is 37". The connector before the digits is optional so bare
# "invariant count 50" still matches. `count` itself may carry markup —
# "scenario **count**: 9" puts the closing `**` between the keyword and the
# colon, where no whitespace follows to let the gap absorb it.
NOUN_COUNT_PHRASE = re.compile(
    rf"\b(?P<noun>invariant|scenario)s?{WRAPPED_GAP}count{MARKUP}{WRAPPED_GAP}?"
    rf"(?:is|of|:|=)?{WRAPPED_GAP}?(?P<number>[0-9]{{1,4}}){NOT_PARTIAL_NUMBER}",
    re.IGNORECASE,
)
# The same claim with the words the other way round: "count of scenarios: 38",
# "the count of invariants is 51". Neither existing pattern reaches this — the
# noun follows `count` rather than leading it, and the number is too far from
# the noun for `NUMBER_BEFORE_NOUN` to bridge.
COUNT_OF_NOUN_PHRASE = re.compile(
    rf"\bcount{MARKUP}{WRAPPED_GAP}of{WRAPPED_GAP}(?P<noun>invariant|scenario)s?"
    rf"{WRAPPED_GAP}?(?:is|of|:|=)?{WRAPPED_GAP}?(?P<number>[0-9]{{1,4}}){NOT_PARTIAL_NUMBER}",
    re.IGNORECASE,
)


class CountCheckError(RuntimeError):
    """Ground truth (a catalog or the tracked-file inventory) is unusable."""


def tracked_markdown_files() -> list[Path]:
    """Return every tracked Markdown file, via Git's own inventory.

    A plain directory walk from the repository root would also read Markdown
    left in a sibling `.claude/worktrees/` checkout of this same repository.
    Git's tracked-file list is scoped to this branch's index and excludes an
    untracked sibling worktree entirely — the same discipline
    `scripts/check_docs_consistency.py` documents and tests for its own
    Markdown discovery.
    """
    result = subprocess.run(
        ["git", "ls-files", "-z", "--", "*.md"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or "git ls-files failed"
        raise CountCheckError(f"tracked-file discovery failed: {detail}")
    labels = [label for label in result.stdout.split("\0") if label]
    if not labels:
        raise CountCheckError("git ls-files returned no Markdown files")
    return [Path(label) for label in labels]


def actual_invariant_count() -> int:
    """Return the number of distinct rows in the generated invariant index.

    Literal content is masked first, on the same grounds as `find_stated_counts`
    below, and through the same `mask_block_content`: a documented example of
    the row format is a sample, and a row inside an HTML comment is a draft.
    Counting either would inflate ground truth itself and so fail every
    accurate stated count in the tree — the loudest possible failure mode.
    """
    text = mask_block_content(INVARIANTS.read_text(encoding="utf-8"))
    tags = set(INVARIANT_ROW.findall(text))
    if not tags:
        raise CountCheckError(f"{INVARIANTS} has no parseable INV-NNN rows")
    return len(tags)


def actual_scenario_count() -> int:
    """Return the number of distinct `## S<N>` scenario headings.

    Literal content is masked for the same reason as in
    `actual_invariant_count`: a `## S99 — Example` inside a fence or an HTML
    comment renders as code or not at all, names no scenario, and must not
    enlarge the catalog it is only illustrating.
    """
    text = mask_block_content(SCENARIOS.read_text(encoding="utf-8"))
    tags = set(SCENARIO_HEADING.findall(text))
    if not tags:
        raise CountCheckError(f"{SCENARIOS} has no parseable scenario headings")
    return len(tags)


def line_number_at(text: str, offset: int) -> int:
    """Return the 1-based line the offset falls on."""
    return text.count("\n", 0, offset) + 1


def as_one_phrase(matched: str) -> str:
    """Collapse a match that spans a wrapped line into one reportable phrase.

    Quote markers the wrap carried, and the inline markup the patterns now step
    over, are dropped: a claim written "There are **51**\ninvariants" inside a
    nested quote reports as "51 invariants", and a reference-linked number
    reports as "51 invariants" rather than "51][index invariants". The same
    constructs the gap steps over are the ones removed here, so the two cannot
    drift; every word the document actually states is still quoted back.
    """
    without_markup = MARKUP_CONSTRUCT.sub(" ", matched)
    return " ".join(word for word in without_markup.split() if set(word) != {">"})


def find_stated_counts(path: Path) -> list[tuple[int, str, int, str]]:
    """Return (line, noun, stated count, matched text) for one Markdown file.

    The whole document is scanned at once rather than line by line, because a
    statement wrapped between its number and its noun is still that statement.
    Every form of literal content is masked first, not just fenced blocks:
    `mask_block_content` covers fences, HTML comments, raw HTML blocks and
    indented code, and `mask_inline_code` covers backtick spans. All of them
    blank in place — same length, same line breaks — so offsets still name the
    right line, and they are reused rather than re-approximated: they already
    handle `~~~` fences, fences longer than three characters, and fences nested
    in block quotes and list items, none of which an opening-delimiter toggle
    gets right. A code example, a commented-out draft, or an inline
    `50 invariants` is not a claim about the catalog.

    A file opening with the non-authoritative-planning banner states nothing at
    all and yields no counts. AGENTS.md exempts those scratchpads from
    consistency review and lets them be revised freely, so a backlog item
    reading "5 scenarios" is a work quantity, not a claim about the catalog.
    The banner test is imported from `generate_invariants.py`, which already
    applies it when validating invariant references, so both checks exempt
    exactly the same set of files.
    """
    raw = path.read_text(encoding="utf-8", errors="replace")
    if has_non_authoritative_planning_banner(raw):
        return []
    text = mask_inline_code(mask_block_content(raw))
    found: list[tuple[int, str, int, str]] = []
    # Every pattern names its two captures `noun` and `number`, so the three
    # can be read the same way regardless of which order the words fall in.
    for pattern in (NUMBER_BEFORE_NOUN, NOUN_COUNT_PHRASE, COUNT_OF_NOUN_PHRASE):
        for match in pattern.finditer(text):
            noun = (
                "invariant"
                if match.group("noun").lower().startswith("invariant")
                else "scenario"
            )
            found.append(
                (
                    line_number_at(text, match.start()),
                    noun,
                    int(match.group("number")),
                    as_one_phrase(match.group(0)),
                )
            )
    return found


def main() -> int:
    try:
        actual = {
            "invariant": actual_invariant_count(),
            "scenario": actual_scenario_count(),
        }
        files = tracked_markdown_files()
    except (CountCheckError, OSError) as error:
        print(f"invariant/scenario count check FAILED: {error}")
        return 1

    failures: list[str] = []
    for path in files:
        # A tracked path can be unreadable while the index still lists it —
        # an unstaged deletion during local validation is the ordinary way.
        # That is reported as a failure like any other rather than raised: a
        # traceback would replace the whole report, including the findings
        # from every file that read fine.
        try:
            stated_counts = find_stated_counts(path)
        except OSError as error:
            failures.append(
                f"{path.as_posix()}: tracked but could not be read "
                f"({error.__class__.__name__})"
            )
            continue
        for line_number, noun, stated, matched in stated_counts:
            if stated != actual[noun]:
                failures.append(
                    f'{path.as_posix()}:{line_number}: states "{matched}", but '
                    f"the current {noun} catalog has {actual[noun]}"
                )

    if failures:
        print("invariant/scenario count check FAILED — a stated count is stale:")
        for failure in sorted(failures):
            print(f"  - {failure}")
        print(
            "Update the stated count, or reword to point at the catalog instead "
            "of restating it: docs/invariants.md is generated by "
            "scripts/generate_invariants.py --write; docs/scenarios.md scenarios "
            "are counted by their own `## S<N>` headings."
        )
        return 1
    print(
        "invariant/scenario count check passed "
        f"({actual['invariant']} invariants, {actual['scenario']} scenarios)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
