#!/usr/bin/env python3
"""Generate the checked invariant-test index from Rust test annotations."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from check_docs_consistency import (
    TrackedFilesError,
    markdown_sources,
    mask_block_content,
    rust_comment_text,
    rust_invariant_test_files,
    rust_sources,
)

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = Path("docs/invariants.md")
INVARIANT_REFERENCE = re.compile(
    r"(?<![A-Za-z0-9])INV-[0-9]{3}(?![A-Za-z0-9])"
)
NON_AUTHORITATIVE_PLANNING_BANNER = re.compile(
    r"\bnon-authoritative(?:-| )planning\b", re.IGNORECASE
)


def has_non_authoritative_planning_banner(text: str) -> bool:
    """Return whether the file head marks its prose as a planning scratchpad."""
    head = "\n".join(text.splitlines()[:12])
    return NON_AUTHORITATIVE_PLANNING_BANNER.search(head) is not None


def orphan_invariant_references(root: Path) -> dict[str, tuple[str, ...]]:
    """Return prose INV references that have no tagged Rust test."""
    rust = rust_sources(root)
    tested = {tag for tag, _source in rust_invariant_test_files(rust).keys()}
    references: dict[str, set[str]] = {}

    def collect(label: str, text: str) -> None:
        for number, line in enumerate(text.splitlines(), start=1):
            for match in INVARIANT_REFERENCE.finditer(line):
                tag = match.group(0)
                if tag not in tested:
                    references.setdefault(tag, set()).add(f"{label}:{number}")

    for source in markdown_sources(root):
        if source == root / OUTPUT:
            continue
        raw = source.read_text(encoding="utf-8")
        if has_non_authoritative_planning_banner(raw):
            continue
        collect(source.relative_to(root).as_posix(), mask_block_content(raw))
    for source in rust:
        collect(source.label, rust_comment_text(source.text))
    return {
        tag: tuple(sorted(locations))
        for tag, locations in sorted(references.items())
    }


def render(root: Path) -> str:
    """Render the complete INV-tag-to-test-file index."""
    by_tag: dict[str, set[str]] = {}
    for tag, source in rust_invariant_test_files(rust_sources(root)).keys():
        by_tag.setdefault(tag, set()).add(source)

    rows: list[tuple[str, str]] = []
    for tag in sorted(by_tag):
        links = ", ".join(
            f"[`{source}`](../{source})" for source in sorted(by_tag[tag])
        )
        rows.append((tag, links))

    id_width = max([len("ID"), *(len(tag) for tag, _ in rows)])
    enforcement_width = max(
        [len("Enforcement"), *(len(enforcement) for _, enforcement in rows)]
    )
    lines = [
        "# Invariant test index",
        "",
        "<!-- Generated by scripts/generate_invariants.py; do not edit. -->",
        "",
        "Browse the CI-executed INV-tagged tests that enforce each law below. The",
        "[testing-style rules](agents/testing-style.md#split-versus-unroll) own tag",
        "binding and regeneration.",
        "",
        f"| {'ID'.ljust(id_width)} | {'Enforcement'.ljust(enforcement_width)} |",
        f"| {'-' * id_width} | {'-' * enforcement_width} |",
    ]
    lines.extend(
        f"| {tag.ljust(id_width)} | {enforcement.ljust(enforcement_width)} |"
        for tag, enforcement in rows
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--check",
        action="store_true",
        help="fail unless docs/invariants.md matches the code-derived index",
    )
    mode.add_argument(
        "--write",
        action="store_true",
        help="replace docs/invariants.md with the code-derived index",
    )
    arguments = parser.parse_args()

    try:
        orphans = orphan_invariant_references(ROOT)
        expected = render(ROOT)
    except TrackedFilesError as error:
        print(f"invariant index check FAILED: {error}", file=sys.stderr)
        return 1
    if orphans:
        print(
            "INV references without tagged Rust tests:",
            file=sys.stderr,
        )
        for tag, locations in orphans.items():
            print(f"  {tag}: {', '.join(locations)}", file=sys.stderr)
        return 1

    destination = ROOT / OUTPUT
    if arguments.write:
        destination.write_text(expected, encoding="utf-8")
        print(f"wrote {OUTPUT}")
        return 0

    actual = destination.read_text(encoding="utf-8")
    if actual != expected:
        print(
            f"{OUTPUT} is stale; run "
            "`python3 scripts/generate_invariants.py --write`",
            file=sys.stderr,
        )
        return 1
    print("invariant test index is current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
