#!/usr/bin/env python3
"""Render the configured crates' public declarations from rustdoc JSON."""

import argparse
import json
import os
import re
import subprocess
import tempfile
import textwrap
import tomllib
from collections import Counter, defaultdict
from pathlib import Path

from domain_spine_digest import AUTO_TRAIT, BLANKET_TRAIT

ROOT = Path(__file__).resolve().parents[1]
HEADER = '<!-- generated by scripts/render_domain_spine.py, do not edit -->\n'
MAX_LINES = 2000
MAX_BYTES = 120_000


def configuration():
    return tomllib.loads((ROOT / 'docs/api/crates.toml').read_text())


def build_json(crate, *, workspace=ROOT, target=None):
    target = target or Path(os.environ.get('CARGO_TARGET_DIR', ROOT / 'target'))
    target = target.resolve()
    # Cargo rejects feature selection for this dependency outside the workspace.
    features = [] if crate == 'signalbox-file-media-linux-sandbox' else ['--all-features']
    # These crates use Tokio macros enabled only by their dev-dependencies.
    if crate in {
        'signalbox-blob-store', 'signalbox-blob-store-s3',
    }:
        features += ['--features', 'tokio/macros']
    subprocess.run([
        'cargo', '+' + configuration()['rustdoc_toolchain'], 'rustdoc', '--locked', '--manifest-path',
        str(workspace / 'Cargo.toml'), '--target-dir', str(target),
        '-p', crate, '--lib', *features, '--',
        '-Z', 'unstable-options', '--output-format', 'json',
    ], check=True, env={**os.environ, 'RUSTC_WRAPPER': ''})
    return target / 'doc' / f"{crate.replace('-', '_')}.json"


def page(title, blocks):
    return HEADER + f'\n# {title}\n\n' + '\n\n'.join(blocks) + '\n'


def fits(text):
    return len(text.splitlines()) < MAX_LINES and len(text.encode()) < MAX_BYTES


def rust_string(value):
    escapes = {'"': '\\"', '\\': '\\\\', '\n': '\\n', '\r': '\\r', '\t': '\\t'}
    return '"' + ''.join(escapes.get(char, f'\\u{{{ord(char):x}}}' if ord(char) < 32 else char)
                         for char in value) + '"'


def cfg_attributes(attribute):
    if not attribute.startswith('#[attr = CfgTrace(['):
        return []
    value = attribute.removeprefix('#[attr = CfgTrace([').removesuffix('])]')
    value = re.sub(r', (?:span: )?[^,\n]*? \(#\d+\)', '', value)
    string = r'"(?:\\.|[^"\\])*"'
    name_value = rf'NameValue \{{ name: ({string}), value: (None|Some\(({string})\)) \}}'
    tokens = re.findall(rf'{name_value}|(All\(\[|Any\(\[|Not\(|\]\)|\)|,)', value)
    position = 0

    def predicate():
        nonlocal position
        name, _, literal, token = tokens[position]
        position += 1
        if name:
            return json.loads(name) + (' = ' + literal if literal else '')
        if token == 'Not(':
            result = 'not(' + predicate() + ')'
            assert tokens[position][3] == ')'
            position += 1
            return result
        assert token in {'All([', 'Any(['}, token
        parts = predicates('])')
        return token[:3].lower() + '(' + ', '.join(parts) + ')'

    def predicates(ending=None):
        nonlocal position
        result = []
        while position < len(tokens) and tokens[position][3] != ending:
            result.append(predicate())
            if position < len(tokens) and tokens[position][3] == ',':
                position += 1
        if ending:
            assert position < len(tokens) and tokens[position][3] == ending
            position += 1
        return result

    return ['#[cfg(' + condition + ')]' for condition in predicates()]


def attributes(item):
    result = []
    for attribute in item['attrs']:
        if attribute == 'non_exhaustive':
            result.append('#[non_exhaustive]')
        elif isinstance(attribute, dict) and 'other' in attribute:
            result.extend(cfg_attributes(attribute['other']))
        elif isinstance(attribute, dict) and 'must_use' in attribute:
            reason = attribute['must_use']['reason']
            result.append('#[must_use' + (' = ' + rust_string(reason) if reason is not None else '') + ']')
        elif isinstance(attribute, dict) and 'repr' in attribute:
            value = attribute['repr']
            parts = [] if value['kind'] == 'rust' else [{'c': 'C'}.get(value['kind'], value['kind'])]
            parts += [f'{key}({value[key]})' for key in ('align', 'packed') if value[key] is not None]
            if value['int']:
                parts.append(value['int'])
            result.append('#[repr(' + ', '.join(parts or ['Rust']) + ')]')
    if item.get('deprecation'):
        parts = [key + ' = ' + rust_string(value) for key, value in item['deprecation'].items() if value is not None]
        result.append('#[deprecated' + ('(' + ', '.join(parts) + ')' if parts else '') + ']')
    return ''.join(value + '\n' for value in result)


def item_cfg(item):
    return tuple(condition.removeprefix('#[cfg(').removesuffix(')]')
                 for attribute in item['attrs'] if isinstance(attribute, dict)
                 for condition in cfg_attributes(attribute.get('other', '')))


def contains_generic(value, name):
    if isinstance(value, dict):
        return value.get('generic') == name or any(contains_generic(child, name) for child in value.values())
    return isinstance(value, list) and any(contains_generic(child, name) for child in value)


def format_rust(code):
    with tempfile.TemporaryDirectory(prefix='domain-spine-rustfmt-') as temporary:
        path = Path(temporary) / 'declarations.rs'
        path.write_text(code + '\n')
        result = subprocess.run([
            'rustfmt', '--quiet', '--edition', '2021', '--emit', 'stdout',
            '--config', 'max_width=100', str(path),
        ], check=False, capture_output=True, text=True)
    if result.returncode == 0:
        return result.stdout.rstrip()
    fallback = []
    for line in code.splitlines():
        indent = line[:len(line) - len(line.lstrip())]
        if len(line) > 100 and not line.lstrip().startswith(('//', '#[')):
            fallback.append(textwrap.fill(
                line, width=100, subsequent_indent=indent + '    ',
                break_long_words=False, break_on_hyphens=False,
            ))
        else:
            fallback.append(line)
    return '\n'.join(fallback).rstrip()


class Renderer:
    def __init__(self, document, public_exports=None):
        self.index = document['index']
        self.paths = document['paths']
        self.root = self.item(document['root'])
        self.crate_id = self.root['crate_id']
        self.crate = self.root['name']
        self.public_exports = public_exports or {}
        self.root_exports = {}
        for identity in self.root['inner']['module']['items']:
            item = self.item(identity)
            if item['visibility'] != 'public':
                continue
            export = item['inner'].get('use')
            target = export['id'] if export else identity
            if target is None or str(target) not in self.index:
                continue
            definition = self.item(target)
            if definition['crate_id'] != self.crate_id or (export and export['is_glob']):
                continue
            name = export['name'] if export else item['name']
            if str(target) not in self.root_exports or name == definition['name']:
                self.root_exports[str(target)] = name
        routes = defaultdict(list)

        def visit(identity, inherited=(), ancestors=()):
            if identity in ancestors:
                return
            item = self.item(identity)
            conditions = tuple(dict.fromkeys(inherited + item_cfg(item)))
            routes[str(identity)].append(conditions)
            body = item['inner']
            if 'module' in body:
                for child in body['module']['items']:
                    visit(child, conditions, ancestors + (identity,))
            elif 'use' in body and body['use']['id'] is not None:
                target = self.index.get(str(body['use']['id']))
                if target and target['crate_id'] == self.crate_id:
                    visit(target['id'], conditions, ancestors + (identity,))

        visit(self.root['id'])
        self.conditions = {}
        for identity, alternatives in routes.items():
            alternatives = list(dict.fromkeys(alternatives))
            self.conditions[identity] = () if () in alternatives else alternatives[0] if len(alternatives) == 1 else (
                'any(' + ', '.join('all(' + ', '.join(route) + ')' for route in alternatives) + ')',)

    def attributes(self, item):
        conditions = self.conditions.get(str(item['id']))
        if conditions is None:
            return attributes(item)
        ungated = {**item, 'attrs': [attribute for attribute in item['attrs']
                                   if not (isinstance(attribute, dict)
                                           and attribute.get('other', '').startswith('#[attr = CfgTrace(['))]}
        return ''.join('#[cfg(' + condition + ')]\n' for condition in conditions) + attributes(ungated)

    def item(self, identity):
        return self.index[str(identity)]

    def exports(self):
        result = {}

        def visit(identity, public, ancestors=()):
            if identity in ancestors:
                return
            item = self.item(identity)
            if item['crate_id'] != self.crate_id:
                return
            kind, body = next(iter(item['inner'].items()))
            if kind == 'use':
                target = body['id']
                if target is not None and str(target) in self.index:
                    visit(target, public if body['is_glob'] else public + [body['name']], ancestors + (identity,))
                return
            definition = self.paths.get(str(identity))
            if definition:
                key = '::'.join(definition['path'])
                candidate = '::'.join(public)
                previous = result.get(key)
                if previous is None or (candidate.count('::'), candidate) < (previous.count('::'), previous):
                    result[key] = candidate
            if kind == 'module':
                for child in body['items']:
                    definition = self.item(child)
                    name = [] if 'use' in definition['inner'] else [definition['name']]
                    visit(child, public + name, ancestors + (identity,))

        visit(self.root['id'], [self.crate])
        return result

    def full_path(self, path):
        summary = self.paths.get(str(path['id']))
        return '::'.join(summary['path']) if summary else path['path']

    def path(self, path):
        if str(path['id']) in self.root_exports:
            return self.root_exports[str(path['id'])] + self.args(path.get('args'))
        full = self.full_path(path)
        if full in self.public_exports:
            return self.public_exports[full].removeprefix(self.crate + '::') + self.args(path.get('args'))
        parts = full.split('::')
        parts = parts[1:] if parts[0] == self.crate else parts[-2:]
        return '::'.join(parts) + self.args(path.get('args'))

    def term(self, term):
        if 'type' in term:
            return self.type(term['type'])
        return term['constant']['expr']

    def args(self, args):
        if args is None:
            return ''
        if args == 'return_type_notation':
            return '(..)'
        if 'parenthesized' in args:
            value = args['parenthesized']
            return '(' + ', '.join(map(self.type, value['inputs'])) + ')' + self.output(value['output'])
        value = args['angle_bracketed']
        rendered = []
        for arg in value['args']:
            kind, body = next(iter(arg.items())) if isinstance(arg, dict) else (arg, None)
            rendered.append(self.type(body) if kind == 'type' else body['expr'] if kind == 'const' else '_' if kind == 'infer' else body)
        for constraint in value['constraints']:
            binding = constraint['binding']
            rendered.append(constraint['name'] + self.args(constraint['args']) + (
                ' = ' + self.term(binding['equality']) if 'equality' in binding
                else ': ' + self.bounds(binding['constraint'])))
        return '<' + ', '.join(rendered) + '>' if rendered else ''

    def type(self, value):
        if value == 'infer':
            return '_'
        kind, body = next(iter(value.items()))
        if kind in {'generic', 'primitive'}:
            return body
        if kind == 'resolved_path':
            return self.path(body)
        if kind in {'borrowed_ref', 'raw_pointer'}:
            pointee = self.type(body['type'])
            if pointee.startswith(('dyn ', 'impl ')) and ' + ' in pointee:
                pointee = '(' + pointee + ')'
            if kind == 'raw_pointer':
                return ('*mut ' if body['is_mutable'] else '*const ') + pointee
            return '&' + ((body['lifetime'] + ' ') if body['lifetime'] else '') + ('mut ' if body['is_mutable'] else '') + pointee
        if kind == 'tuple':
            return '(' + ', '.join(map(self.type, body)) + (',' if len(body) == 1 else '') + ')'
        if kind == 'slice':
            return '[' + self.type(body) + ']'
        if kind == 'array':
            return '[' + self.type(body['type']) + '; ' + body['len'] + ']'
        if kind == 'impl_trait':
            return 'impl ' + self.bounds(body)
        if kind == 'dyn_trait':
            traits = [self.for_params(t['generic_params']) + self.path(t['trait']) for t in body['traits']]
            return 'dyn ' + ' + '.join(traits + ([body['lifetime']] if body['lifetime'] else []))
        if kind == 'qualified_path':
            subject = self.type(body['self_type'])
            owner = '<' + subject + ' as ' + self.path(body['trait']) + '>' if body['trait'] else subject
            return owner + '::' + body['name'] + self.args(body['args'])
        if kind == 'function_pointer':
            return self.for_params(body['generic_params']) + self.modifiers(body['header']) + 'fn' + self.signature(body['sig'])
        raise ValueError(f'Unsupported rustdoc type: {value}')

    def bounds(self, bounds):
        result = []
        for bound in bounds:
            kind, body = next(iter(bound.items()))
            if kind == 'trait_bound':
                modifier = {'none': '', 'maybe': '?', 'maybe_const': '~const '}[body['modifier']]
                result.append(self.for_params(body['generic_params']) + modifier + self.path(body['trait']))
            elif kind == 'outlives':
                result.append(body)
            elif kind == 'use':
                result.append('use<' + ', '.join(next(iter(p.values())) for p in body) + '>')
            else:
                raise ValueError(f'Unsupported bound: {bound}')
        return ' + '.join(result)

    def params(self, params):
        result = []
        for param in params:
            kind, body = next(iter(param['kind'].items()))
            name = param['name']
            if kind == 'type':
                if body['is_synthetic']:
                    continue
                bounds = self.bounds(body['bounds'])
                name += ': ' + bounds if bounds else ''
                name += ' = ' + self.type(body['default']) if body['default'] else ''
            elif kind == 'lifetime':
                name += ': ' + ' + '.join(body['outlives']) if body['outlives'] else ''
            elif kind == 'const':
                name = 'const ' + name + ': ' + self.type(body['type'])
                name += ' = ' + body['default'] if body['default'] else ''
            result.append(name)
        return '<' + ', '.join(result) + '>' if result else ''

    def for_params(self, params):
        value = self.params(params)
        return 'for' + value + ' ' if value else ''

    def where(self, generics):
        result = []
        for predicate in generics['where_predicates']:
            kind, body = next(iter(predicate.items()))
            if kind == 'bound_predicate':
                result.append(self.for_params(body['generic_params']) + self.type(body['type']) + ': ' + self.bounds(body['bounds']))
            elif kind == 'lifetime_predicate':
                result.append(body['lifetime'] + ': ' + ' + '.join(body['outlives']))
            elif kind == 'eq_predicate':
                result.append(self.type(body['lhs']) + ' = ' + self.term(body['rhs']))
            else:
                raise ValueError(f'Unsupported predicate: {predicate}')
        return ' where ' + ', '.join(result) if result else ''

    def modifiers(self, header):
        result = ''.join(word + ' ' for word in ('const', 'async', 'unsafe') if header['is_' + word])
        abi = header['abi']
        if abi != 'Rust':
            if isinstance(abi, dict):
                name, options = next(iter(abi.items()))
                abi = options if name == 'Other' else ('C' if name == 'C' else name.lower()) + ('-unwind' if options['unwind'] else '')
            result += f'extern "{abi}" '
        return result

    def output(self, output):
        return ' -> ' + self.type(output) if output is not None else ''

    def signature(self, sig):
        inputs = []
        for name, value in sig['inputs']:
            rendered = self.type(value)
            if name == 'self' and rendered == 'Self':
                inputs.append('self')
            elif name == 'self' and rendered.startswith('&') and rendered.endswith('Self'):
                inputs.append(rendered.removesuffix('Self') + 'self')
            else:
                inputs.append(f'{name}: {rendered}')
        if sig['is_c_variadic']:
            inputs.append('...')
        return '(' + ', '.join(inputs) + ')' + self.output(sig['output'])

    def field(self, identity, *, named=False, public=False):
        if identity is None:
            return '/* private */'
        item = self.item(identity)
        prefix = ('pub ' if public else '') + item['name'] + ': ' if named else ('pub ' if public else '')
        return self.attributes(item) + prefix + self.type(item['inner']['struct_field'])

    def shape(self, kind, *, public=False):
        if kind == 'unit':
            return ';'
        if kind == 'plain':
            return ''
        if 'tuple' in kind:
            fields = [self.field(i, public=public and i is not None) for i in kind['tuple']]
            return '(' + ', '.join(fields) + ')'
        body = kind.get('plain', kind.get('struct'))
        fields = [self.field(i, named=True, public=public) for i in body['fields']]
        if public:
            lines = [textwrap.indent(field + ',', '    ') for field in fields]
            if body['has_stripped_fields']:
                lines.append('    /* private */')
            return ' {\n' + '\n'.join(lines) + '\n}'
        if body['has_stripped_fields']:
            fields.append('/* private */')
        return ' { ' + ', '.join(fields) + ' }'

    def declaration(self, item, *, associated=False, trait_definition=False):
        return self.attributes(item) + self.declaration_body(item, associated=associated, trait_definition=trait_definition)

    def declaration_body(self, item, *, associated=False, trait_definition=False):
        kind, body = next(iter(item['inner'].items()))
        name = body['name'] if kind == 'use' else item['name']
        generics = body.get('generics', {'params': [], 'where_predicates': []})
        generic_name = name + self.params(generics['params'])
        where = self.where(generics)
        prefix = '' if associated else 'pub '
        if kind == 'function':
            ending = ' {\n    /* provided */\n}' if trait_definition and body['has_body'] else ';'
            return prefix + self.modifiers(body['header']) + 'fn ' + generic_name + self.signature(body['sig']) + where + ending
        if kind == 'struct':
            shape = self.shape(body['kind'], public=True)
            if isinstance(body['kind'], dict) and 'tuple' in body['kind']:
                return 'pub struct ' + generic_name + shape + where + ';'
            return 'pub struct ' + generic_name + where + shape
        if kind == 'enum':
            variants = []
            for identity in body['variants']:
                variant = self.item(identity)
                value = variant['inner']['variant']
                line = variant['name'] + self.shape(value['kind'])
                if value['discriminant']:
                    line += ' = ' + value['discriminant']['expr']
                variants.append(textwrap.indent(self.attributes(variant) + line + ',', '    '))
            return 'pub enum ' + generic_name + where + ' {\n' + '\n'.join(variants) + '\n}'
        if kind == 'trait':
            bounds = self.bounds(body['bounds'])
            header = 'pub ' + ('unsafe ' if body['is_unsafe'] else '') + ('auto ' if body['is_auto'] else '') + 'trait ' + generic_name
            header += ': ' + bounds if bounds else ''
            methods = [self.declaration(self.item(i), associated=True, trait_definition=True) for i in body['items']]
            return header + where + ' {\n' + '\n'.join(textwrap.indent(m, '    ') for m in methods) + '\n}'
        if kind in {'type_alias', 'assoc_type'}:
            bounds = self.bounds(body.get('bounds', []))
            return prefix + 'type ' + generic_name + (': ' + bounds if bounds else '') + where + (' = ' + self.type(body['type']) if body.get('type') else '') + ';'
        if kind in {'constant', 'assoc_const', 'static'}:
            return prefix + ('static ' if kind == 'static' else 'const ') + ('mut ' if body.get('is_mutable') else '') + name + ': ' + self.type(body['type']) + ';'
        if kind == 'use':
            source = body['source'].removeprefix(self.crate + '::')
            return 'pub use ' + source + ('::*' if body['is_glob'] else ' as ' + body['name'] if source.split('::')[-1] != body['name'] else '') + ';'
        raise ValueError(f'Unsupported public item: {kind} {name}')

    def source_order(self, item):
        span = item['span']
        return (span['filename'], *span['begin']) if span else ('', 0, 0)

    def impl_block(self, item, conditions=()):
        body = item['inner']['impl']
        trait = body['trait']
        generics = body['generics']
        header = ('unsafe ' if body['is_unsafe'] else '') + 'impl' + self.params(generics['params']) + ' '
        if trait:
            header += ('!' if body['is_negative'] else '') + self.path(trait) + ' for '
        header += self.type(body['for']) + self.where(generics)
        methods = [self.declaration(self.item(i), associated=bool(trait)) for i in body['items']
                   if trait or self.item(i)['visibility'] == 'public']
        cfg = ''.join('#[cfg(' + condition + ')]\n' for condition in dict.fromkeys(conditions + item_cfg(item)))
        return cfg + (header + ' {\n' + '\n'.join(textwrap.indent(m, '    ') for m in methods) + '\n}' if methods else header + ' {}')

    def block(self, item):
        kind, body = next(iter(item['inner'].items()))
        declarations = [self.declaration(item)]
        derives = []
        implementations = []
        for identity in body.get('impls', []):
            implementation = self.item(identity)
            subject = implementation['inner']['impl']['for'].get('resolved_path')
            owner = self.index.get(str(subject['id'])) if subject else None
            if not owner or owner['crate_id'] != self.crate_id or owner['id'] == item['id']:
                implementations.append(implementation)
        if kind == 'trait':
            for identity in body['implementations']:
                implementation = self.item(identity)
                subject = implementation['inner']['impl']['for'].get('resolved_path')
                local_type = subject and str(subject['id']) in self.index and self.item(subject['id'])['crate_id'] == self.crate_id
                if implementation['crate_id'] == self.crate_id and not local_type:
                    implementations.append(implementation)
        for implementation in sorted(implementations, key=self.source_order):
            value = implementation['inner']['impl']
            trait = value['trait']
            full = self.full_path(trait) if trait else ''
            if value['is_synthetic'] or AUTO_TRAIT.fullmatch(full):
                continue
            if value['blanket_impl'] and BLANKET_TRAIT.fullmatch(full):
                continue
            if value['blanket_impl'] and trait and self.paths.get(str(trait['id']), {}).get('crate_id') != self.crate_id:
                if any('type' in param['kind'] and not contains_generic(
                        [value['for'], trait], param['name'])
                       for param in value['generics']['params']):
                    continue
            if 'automatically_derived' in implementation['attrs']:
                derives.append(self.path(trait))
            else:
                declarations.append(self.impl_block(implementation, self.conditions.get(str(item['id']), item_cfg(item))))
        if derives:
            declarations.insert(1, '// derives: ' + ', '.join(dict.fromkeys(derives)))
        name = body['name'] if kind == 'use' else item['name']
        return '## ' + name + '\n\n```rust\n' + format_rust('\n'.join(declarations)) + '\n```'

    def modules(self):
        result = defaultdict(list)
        seen = set()

        def visit(identity, module='root'):
            item = self.item(identity)
            kind, body = next(iter(item['inner'].items()))
            if kind == 'module':
                if identity != self.root['id']:
                    module = item['name'] if module == 'root' else module
                    result[module]
                for child in body['items']:
                    visit(child, module)
                return
            if kind == 'use' and body['id'] is not None and str(body['id']) in self.index:
                target = self.item(body['id'])
                if target['crate_id'] == self.crate_id:
                    visit(body['id'], module)
                    if body['name'] == target['name'] or body['is_glob']:
                        return
            if identity in seen:
                return
            seen.add(identity)
            span = item['span']
            if span and module == 'root':
                filename = span['filename'].split('src/', 1)[-1]
                module = filename.split('/')[0].removesuffix('.rs')
                module = 'root' if module == 'lib' else module
            result[module].append(item)

        visit(self.root['id'])
        return {name: sorted(items, key=self.source_order) for name, items in result.items()}

    def files(self, crate):
        files = {}
        rows = []
        for module, items in self.modules().items():
            blocks = [self.block(item) for item in items]
            whole = page(module, blocks)
            links = []
            previous = list((ROOT / 'docs/api' / crate / module).glob('*.md'))
            if fits(whole) and not previous:
                files[f'{module}.md'] = whole
                links.append(f'[{module}]({module}.md)')
            else:
                groups = defaultdict(list)
                for item, block in zip(items, blocks):
                    kind = next(iter(item['inner']))
                    groups['traits' if kind == 'trait' else 'functions' if kind in {'function', 'constant', 'static'} else 'types'].append(block)
                for kind, group in groups.items():
                    parts = sorted((path for path in previous if re.fullmatch(rf'{kind}(?:-\d+)?\.md', path.name)),
                                   key=lambda path: int(path.stem.rpartition('-')[2]) if '-' in path.stem else 1)
                    boundaries = {headings[-1] for path in parts[:-1]
                                  if (headings := re.findall(r'^## (.+)$', path.read_text(), re.MULTILINE))}
                    chunks = [[]]
                    for block in group:
                        if (chunks[-1] and chunks[-1][-1].splitlines()[0].removeprefix('## ') in boundaries
                                or not fits(page(f'{module}: {kind}', chunks[-1] + [block]))):
                            if not chunks[-1]:
                                raise ValueError(f'{module}: one item exceeds the page limits')
                            chunks.append([])
                        chunks[-1].append(block)
                    for number, chunk in enumerate(chunks, 1):
                        suffix = '' if number == 1 else f'-{number}'
                        path = f'{module}/{kind}{suffix}.md'
                        files[path] = page(f'{module}: {kind}{suffix}', chunk)
                        links.append(f'[{kind}{suffix}]({path})')
            counts = Counter(next(iter(item['inner'])) for item in items)
            types = sum(counts[kind] for kind in ('struct', 'enum', 'union', 'type_alias'))
            rows.append(f"| {module} | {types} | {counts['trait']} | {counts['function']} | {', '.join(links)} |")
        files['README.md'] = page(crate, ['| Module | Types | Traits | Functions | Declarations |\n| --- | ---: | ---: | ---: | --- |\n' + '\n'.join(rows)])
        for path, text in files.items():
            if not fits(text):
                raise ValueError(f'{path} exceeds the page limits')
        return files


def write_files(directory, files):
    for old in directory.rglob('*.md'):
        if old.relative_to(directory).as_posix() not in files:
            old.unlink()
    for relative, text in files.items():
        path = directory / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--json-dir', type=Path, help='Read already-built rustdoc JSON instead of building')
    args = parser.parse_args()
    paths = {crate: args.json_dir / f"{crate.replace('-', '_')}.json" if args.json_dir else build_json(crate)
             for crate in configuration()['crates']}
    public_exports = {}
    for path in paths.values():
        renderer = Renderer(json.loads(path.read_text()))
        public_exports.update(renderer.exports())
    for crate, path in paths.items():
        renderer = Renderer(json.loads(path.read_text()), public_exports)
        files = renderer.files(crate)
        write_files(ROOT / 'docs/api' / crate, files)
        print(f'{crate}: {len(files)} Markdown files')


if __name__ == '__main__':
    main()
