#!/usr/bin/env python3
"""Render the configured crates' public declarations from rustdoc JSON."""

import argparse
import json
import os
import subprocess
import tomllib
from collections import Counter, defaultdict
from pathlib import Path

from domain_spine_digest import AUTO_TRAIT, BLANKET_TRAIT

ROOT = Path(__file__).resolve().parents[1]
HEADER = '<!-- generated by scripts/render_domain_spine.py, do not edit -->\n'
MAX_LINES = 800
MAX_BYTES = 120_000


def configuration():
    return tomllib.loads((ROOT / 'docs/api/crates.toml').read_text())


def build_json(crate, *, workspace=ROOT, target=None):
    target = target or Path(os.environ.get('CARGO_TARGET_DIR', ROOT / 'target'))
    target = target.resolve()
    subprocess.run([
        'cargo', '+nightly', 'rustdoc', '--locked', '--manifest-path',
        str(workspace / 'Cargo.toml'), '--target-dir', str(target),
        '-p', crate, '--lib', '--all-features', '--',
        '-Z', 'unstable-options', '--output-format', 'json',
    ], check=True, env={**os.environ, 'RUSTC_WRAPPER': ''})
    return target / 'doc' / f"{crate.replace('-', '_')}.json"


def page(title, blocks):
    return HEADER + f'\n# {title}\n\n' + '\n\n'.join(blocks) + '\n'


def fits(text):
    return len(text.splitlines()) < MAX_LINES and len(text.encode()) < MAX_BYTES


class Renderer:
    def __init__(self, document):
        self.index = document['index']
        self.paths = document['paths']
        self.root = self.item(document['root'])
        self.crate_id = self.root['crate_id']
        self.crate = self.root['name']

    def item(self, identity):
        return self.index[str(identity)]

    def full_path(self, path):
        summary = self.paths.get(str(path['id']))
        return '::'.join(summary['path']) if summary else path['path']

    def path(self, path):
        parts = self.full_path(path).split('::')
        parts = parts[1:] if parts[0] == self.crate else parts[-2:]
        return '::'.join(parts) + self.args(path.get('args'))

    def term(self, term):
        if 'type' in term:
            return self.type(term['type'])
        return term['constant']['expr']

    def args(self, args):
        if args is None:
            return ''
        if args == 'return_type_notation':
            return '(..)'
        if 'parenthesized' in args:
            value = args['parenthesized']
            return '(' + ', '.join(map(self.type, value['inputs'])) + ')' + self.output(value['output'])
        value = args['angle_bracketed']
        rendered = []
        for arg in value['args']:
            kind, body = next(iter(arg.items())) if isinstance(arg, dict) else (arg, None)
            rendered.append(self.type(body) if kind == 'type' else body['expr'] if kind == 'const' else '_' if kind == 'infer' else body)
        for constraint in value['constraints']:
            binding = constraint['binding']
            rendered.append(constraint['name'] + self.args(constraint['args']) + (
                ' = ' + self.term(binding['equality']) if 'equality' in binding
                else ': ' + self.bounds(binding['constraint'])))
        return '<' + ', '.join(rendered) + '>' if rendered else ''

    def type(self, value):
        if value == 'infer':
            return '_'
        kind, body = next(iter(value.items()))
        if kind in {'generic', 'primitive'}:
            return body
        if kind == 'resolved_path':
            return self.path(body)
        if kind == 'borrowed_ref':
            return '&' + ((body['lifetime'] + ' ') if body['lifetime'] else '') + ('mut ' if body['is_mutable'] else '') + self.type(body['type'])
        if kind == 'raw_pointer':
            return ('*mut ' if body['is_mutable'] else '*const ') + self.type(body['type'])
        if kind == 'tuple':
            return '(' + ', '.join(map(self.type, body)) + (',' if len(body) == 1 else '') + ')'
        if kind == 'slice':
            return '[' + self.type(body) + ']'
        if kind == 'array':
            return '[' + self.type(body['type']) + '; ' + body['len'] + ']'
        if kind == 'impl_trait':
            return 'impl ' + self.bounds(body)
        if kind == 'dyn_trait':
            traits = [self.for_params(t['generic_params']) + self.path(t['trait']) for t in body['traits']]
            return 'dyn ' + ' + '.join(traits + ([body['lifetime']] if body['lifetime'] else []))
        if kind == 'qualified_path':
            subject = self.type(body['self_type'])
            owner = '<' + subject + ' as ' + self.path(body['trait']) + '>' if body['trait'] else subject
            return owner + '::' + body['name'] + self.args(body['args'])
        if kind == 'function_pointer':
            return self.for_params(body['generic_params']) + self.modifiers(body['header']) + 'fn' + self.signature(body['sig'])
        raise ValueError(f'Unsupported rustdoc type: {value}')

    def bounds(self, bounds):
        result = []
        for bound in bounds:
            kind, body = next(iter(bound.items()))
            if kind == 'trait_bound':
                modifier = {'none': '', 'maybe': '?', 'maybe_const': '~const '}[body['modifier']]
                result.append(self.for_params(body['generic_params']) + modifier + self.path(body['trait']))
            elif kind == 'outlives':
                result.append(body)
            elif kind == 'use':
                result.append('use<' + ', '.join(next(iter(p.values())) for p in body) + '>')
            else:
                raise ValueError(f'Unsupported bound: {bound}')
        return ' + '.join(result)

    def params(self, params):
        result = []
        for param in params:
            kind, body = next(iter(param['kind'].items()))
            name = param['name']
            if kind == 'type':
                if body['is_synthetic']:
                    continue
                bounds = self.bounds(body['bounds'])
                name += ': ' + bounds if bounds else ''
                name += ' = ' + self.type(body['default']) if body['default'] else ''
            elif kind == 'lifetime':
                name += ': ' + ' + '.join(body['outlives']) if body['outlives'] else ''
            elif kind == 'const':
                name = 'const ' + name + ': ' + self.type(body['type'])
                name += ' = ' + body['default'] if body['default'] else ''
            result.append(name)
        return '<' + ', '.join(result) + '>' if result else ''

    def for_params(self, params):
        value = self.params(params)
        return 'for' + value + ' ' if value else ''

    def where(self, generics):
        result = []
        for predicate in generics['where_predicates']:
            kind, body = next(iter(predicate.items()))
            if kind == 'bound_predicate':
                result.append(self.for_params(body['generic_params']) + self.type(body['type']) + ': ' + self.bounds(body['bounds']))
            elif kind == 'lifetime_predicate':
                result.append(body['lifetime'] + ': ' + ' + '.join(body['outlives']))
            elif kind == 'eq_predicate':
                result.append(self.type(body['lhs']) + ' = ' + self.term(body['rhs']))
            else:
                raise ValueError(f'Unsupported predicate: {predicate}')
        return ' where ' + ', '.join(result) if result else ''

    def modifiers(self, header):
        result = ''.join(word + ' ' for word in ('const', 'async', 'unsafe') if header['is_' + word])
        abi = header['abi']
        if abi != 'Rust':
            if isinstance(abi, dict):
                name, options = next(iter(abi.items()))
                abi = options if name == 'Other' else name.lower() + ('-unwind' if options['unwind'] else '')
            result += f'extern "{abi}" '
        return result

    def output(self, output):
        return ' -> ' + self.type(output) if output is not None else ''

    def signature(self, sig):
        inputs = []
        for name, value in sig['inputs']:
            rendered = self.type(value)
            if name == 'self' and rendered == 'Self':
                inputs.append('self')
            elif name == 'self' and rendered.startswith('&') and rendered.endswith('Self'):
                inputs.append(rendered.removesuffix('Self') + 'self')
            else:
                inputs.append(f'{name}: {rendered}')
        if sig['is_c_variadic']:
            inputs.append('...')
        return '(' + ', '.join(inputs) + ')' + self.output(sig['output'])

    def field(self, identity, *, named=False, public=False):
        if identity is None:
            return '/* private */'
        item = self.item(identity)
        prefix = ('pub ' if public else '') + item['name'] + ': ' if named else ('pub ' if public else '')
        return prefix + self.type(item['inner']['struct_field'])

    def shape(self, kind, *, public=False):
        if kind == 'unit':
            return ';'
        if kind == 'plain':
            return ''
        if 'tuple' in kind:
            fields = [self.field(i, public=public and i is not None) for i in kind['tuple']]
            return '(' + ', '.join(fields) + ')'
        body = kind.get('plain', kind.get('struct'))
        fields = [self.field(i, named=True, public=public) for i in body['fields']]
        if body['has_stripped_fields']:
            fields.append('/* private */')
        return ' { ' + ', '.join(fields) + ' }'

    def declaration(self, item, *, associated=False):
        kind, body = next(iter(item['inner'].items()))
        name = item['name']
        generics = body.get('generics', {'params': [], 'where_predicates': []})
        generic_name = name + self.params(generics['params'])
        where = self.where(generics)
        prefix = '' if associated and kind != 'function' else 'pub '
        if kind == 'function':
            return 'pub ' + self.modifiers(body['header']) + 'fn ' + generic_name + self.signature(body['sig']) + where + ';'
        if kind == 'struct':
            shape = self.shape(body['kind'], public=True)
            if isinstance(body['kind'], dict) and 'tuple' in body['kind']:
                return 'pub struct ' + generic_name + shape + where + ';'
            return 'pub struct ' + generic_name + where + shape
        if kind == 'enum':
            variants = []
            for identity in body['variants']:
                variant = self.item(identity)
                value = variant['inner']['variant']
                line = variant['name'] + self.shape(value['kind'])
                if value['discriminant']:
                    line += ' = ' + value['discriminant']['expr']
                variants.append('    ' + line + ',')
            return 'pub enum ' + generic_name + where + ' {\n' + '\n'.join(variants) + '\n}'
        if kind == 'trait':
            bounds = self.bounds(body['bounds'])
            header = 'pub ' + ('unsafe ' if body['is_unsafe'] else '') + ('auto ' if body['is_auto'] else '') + 'trait ' + generic_name
            header += ': ' + bounds if bounds else ''
            methods = [self.declaration(self.item(i), associated=True) for i in body['items']]
            return header + where + ' {\n' + '\n'.join('    ' + m for m in methods) + '\n}'
        if kind in {'type_alias', 'assoc_type'}:
            bounds = self.bounds(body.get('bounds', []))
            return prefix + 'type ' + generic_name + (': ' + bounds if bounds else '') + where + (' = ' + self.type(body['type']) if body.get('type') else '') + ';'
        if kind in {'constant', 'assoc_const', 'static'}:
            return prefix + ('static ' if kind == 'static' else 'const ') + ('mut ' if body.get('is_mutable') else '') + name + ': ' + self.type(body['type']) + ';'
        if kind == 'use':
            source = body['source'].removeprefix(self.crate + '::')
            return 'pub use ' + source + ('::*' if body['is_glob'] else ' as ' + body['name'] if source.split('::')[-1] != body['name'] else '') + ';'
        raise ValueError(f'Unsupported public item: {kind} {name}')

    def source_order(self, item):
        span = item['span']
        return (span['filename'], *span['begin']) if span else ('', 0, 0)

    def impl_block(self, item):
        body = item['inner']['impl']
        trait = body['trait']
        generics = body['generics']
        header = ('unsafe ' if body['is_unsafe'] else '') + 'impl' + self.params(generics['params']) + ' '
        if trait:
            header += ('!' if body['is_negative'] else '') + self.path(trait) + ' for '
        header += self.type(body['for']) + self.where(generics)
        methods = [self.declaration(self.item(i), associated=True) for i in body['items']
                   if trait or self.item(i)['visibility'] == 'public']
        return header + ' {\n' + '\n'.join('    ' + m for m in methods) + '\n}' if methods else header + ' {}'

    def block(self, item):
        kind, body = next(iter(item['inner'].items()))
        declarations = [self.declaration(item)]
        derives = []
        implementations = [self.item(i) for i in body.get('impls', [])]
        if kind == 'trait':
            for identity in body['implementations']:
                implementation = self.item(identity)
                subject = implementation['inner']['impl']['for'].get('resolved_path')
                local_type = subject and str(subject['id']) in self.index and self.item(subject['id'])['crate_id'] == self.crate_id
                if implementation['crate_id'] == self.crate_id and not local_type:
                    implementations.append(implementation)
        for implementation in sorted(implementations, key=self.source_order):
            value = implementation['inner']['impl']
            trait = value['trait']
            full = self.full_path(trait) if trait else ''
            if value['is_synthetic'] or AUTO_TRAIT.fullmatch(full):
                continue
            if value['blanket_impl'] and BLANKET_TRAIT.fullmatch(full):
                continue
            if 'automatically_derived' in json.dumps(implementation['attrs']) or value['blanket_impl']:
                derives.append(self.path(trait))
            else:
                declarations.append(self.impl_block(implementation))
        if derives:
            declarations.insert(1, '// derives: ' + ', '.join(dict.fromkeys(derives)))
        return '## ' + item['name'] + '\n\n```rust\n' + '\n'.join(declarations) + '\n```'

    def modules(self):
        result = defaultdict(list)
        seen = set()

        def visit(identity, module='root'):
            item = self.item(identity)
            kind, body = next(iter(item['inner'].items()))
            if kind == 'module':
                if identity != self.root['id']:
                    module = item['name'] if module == 'root' else module
                    result[module]
                for child in body['items']:
                    visit(child, module)
                return
            if kind == 'use' and body['id'] is not None and str(body['id']) in self.index:
                target = self.item(body['id'])
                if target['crate_id'] == self.crate_id:
                    visit(body['id'], module)
                    if body['name'] == target['name'] or body['is_glob']:
                        return
            if identity in seen:
                return
            seen.add(identity)
            span = item['span']
            if span and module == 'root':
                filename = span['filename'].split('src/', 1)[-1]
                module = filename.split('/')[0].removesuffix('.rs')
                module = 'root' if module == 'lib' else module
            result[module].append(item)

        visit(self.root['id'])
        return {name: sorted(items, key=self.source_order) for name, items in result.items()}

    def files(self, crate):
        files = {}
        rows = []
        for module, items in self.modules().items():
            blocks = [self.block(item) for item in items]
            whole = page(module, blocks)
            links = []
            if fits(whole):
                files[f'{module}.md'] = whole
                links.append(f'[{module}]({module}.md)')
            else:
                groups = defaultdict(list)
                for item, block in zip(items, blocks):
                    kind = next(iter(item['inner']))
                    groups['traits' if kind == 'trait' else 'functions' if kind in {'function', 'constant', 'static'} else 'types'].append(block)
                for kind, group in groups.items():
                    chunks = [[]]
                    for block in group:
                        if not fits(page(f'{module}: {kind}', chunks[-1] + [block])):
                            if not chunks[-1]:
                                raise ValueError(f'{module}: one item exceeds the page limits')
                            chunks.append([])
                        chunks[-1].append(block)
                    for number, chunk in enumerate(chunks, 1):
                        suffix = '' if number == 1 else f'-{number}'
                        path = f'{module}/{kind}{suffix}.md'
                        files[path] = page(f'{module}: {kind}{suffix}', chunk)
                        links.append(f'[{kind}{suffix}]({path})')
            counts = Counter(next(iter(item['inner'])) for item in items)
            types = sum(counts[kind] for kind in ('struct', 'enum', 'union', 'type_alias'))
            rows.append(f"| {module} | {types} | {counts['trait']} | {counts['function']} | {', '.join(links)} |")
        files['README.md'] = page(crate, ['| Module | Types | Traits | Functions | Declarations |\n| --- | ---: | ---: | ---: | --- |\n' + '\n'.join(rows)])
        for path, text in files.items():
            if not fits(text):
                raise ValueError(f'{path} exceeds the page limits')
        return files


def write_files(directory, files):
    for old in directory.rglob('*.md'):
        if old.relative_to(directory).as_posix() not in files:
            old.unlink()
    for relative, text in files.items():
        path = directory / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--json-dir', type=Path, help='Read already-built rustdoc JSON instead of building')
    args = parser.parse_args()
    for crate in configuration()['crates']:
        path = args.json_dir / f"{crate.replace('-', '_')}.json" if args.json_dir else build_json(crate)
        renderer = Renderer(json.loads(path.read_text()))
        files = renderer.files(crate)
        write_files(ROOT / 'docs/api' / crate, files)
        print(f'{crate}: {len(files)} Markdown files')


if __name__ == '__main__':
    main()
