#!/usr/bin/env python3
"""Prove check_invariant_scenario_counts.py catches a stale stated count.

Each rule gets a positive and a negative case, mirroring
test_check_migration_versions.py: an accurate stated count passes, a stale
one fails naming the file and line, a count inside fenced code is invisible
to the scan, an INV-NNN identifier is never mistaken for a stated count, and
an untracked sibling worktree (the `.claude/worktrees/` pattern this repo
uses for concurrent agent checkouts) is never scanned. Every case runs the
checker as a subprocess against a synthetic Git working tree.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

CHECKER = Path(__file__).resolve().parent / "check_invariant_scenario_counts.py"

INVARIANTS_TEXT = (
    "# Invariant test index\n\n"
    "<!-- Generated by scripts/generate_invariants.py; do not edit. -->\n\n"
    "| ID      | Enforcement                        |\n"
    "| ------- | ----------------------------------- |\n"
    "| INV-001 | tests in [`src/a.rs`](../src/a.rs) |\n"
    "| INV-002 | tests in [`src/b.rs`](../src/b.rs) |\n"
)  # 2 invariants

SCENARIOS_TEXT = (
    "# Design scenarios\n\n"
    "## S01 — First scenario\n\n"
    "Body.\n\n"
    "## S02 — Second scenario\n\n"
    "Body.\n"
)  # 2 scenarios


def git(root: Path, *arguments: str) -> None:
    subprocess.run(
        ["git", "-c", "commit.gpgSign=false", *arguments],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )


def run_checker(root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECKER)],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )


def fixture_root(
    directory: str, extra: dict[str, str] | None = None, *, omit_invariants: bool = False
) -> Path:
    """Build a synthetic repository with the two generated catalogs staged.

    `git ls-files` reads the index, so `git add` (no commit needed) is enough
    to make a fixture file "tracked" for the checker's own discovery; a file
    written but never added stays invisible, which is how the sibling-worktree
    test below proves untracked content is ignored.
    """
    root = Path(directory)
    (root / "docs").mkdir(parents=True)
    if not omit_invariants:
        (root / "docs/invariants.md").write_text(INVARIANTS_TEXT, encoding="utf-8")
    (root / "docs/scenarios.md").write_text(SCENARIOS_TEXT, encoding="utf-8")
    for relative, text in (extra or {}).items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    git(root, "init", "-q")
    git(root, "add", "-A")
    return root


class InvariantScenarioCountCheckerTests(unittest.TestCase):
    def test_no_stated_counts_passes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp, {"AGENTS.md": "# Guidance\n\nSee the catalog.\n"}
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("2 invariants, 2 scenarios", result.stdout)

    def test_accurate_stated_count_passes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        "The catalog defines 2 invariants and 2 scenarios.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_stale_invariant_count_fails(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {"docs/spec/example.md": "The catalog defines 5 invariants today.\n"},
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("docs/spec/example.md:1", result.stdout)
        self.assertIn("5 invariants", result.stdout)
        self.assertIn("current invariant catalog has 2", result.stdout)

    def test_stale_scenario_count_phrase_fails(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(tmp, {"README.md": "scenario count: 9\n"})

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("README.md:1", result.stdout)
        self.assertIn("current scenario catalog has 2", result.stdout)

    def test_count_inside_fenced_code_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        "```text\n5 invariants (example only)\n```\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_invariant_identifier_is_not_mistaken_for_a_count(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp, {"docs/spec/example.md": "See INV-002 for details.\n"}
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_scenario_reference_by_id_is_not_mistaken_for_a_count(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {"docs/spec/example.md": "See the S01 scenario for the walkthrough.\n"},
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_untracked_sibling_worktree_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(tmp)
            sibling = root / ".claude/worktrees/agent-phantom/docs/spec"
            sibling.mkdir(parents=True)
            (sibling / "phantom.md").write_text(
                "The catalog defines 999 invariants.\n", encoding="utf-8"
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_missing_invariants_catalog_fails_loudly(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(tmp, omit_invariants=True)

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("invariants.md", result.stdout)


if __name__ == "__main__":
    unittest.main()
