#!/usr/bin/env python3
"""Prove check_invariant_scenario_counts.py catches a stale stated count.

Each rule gets a positive and a negative case, mirroring
test_check_migration_versions.py: an accurate stated count passes, a stale
one fails naming the file and line, a stale count the formatter wrapped
between its number and its noun still fails while a number and noun in
separate paragraphs do not, a count inside fenced code is invisible to the
scan for every fence shape this repository writes (```` ``` ````, `~~~`,
long fences holding short ones, and fences nested in block quotes and list
items), an INV-NNN identifier is never mistaken for a stated count, and an
untracked sibling worktree (the `.claude/worktrees/` pattern this repo uses
for concurrent agent checkouts) is never scanned. Every case runs the
checker as a subprocess against a synthetic Git working tree, and every
expected total is derived from the fixture rosters rather than restated.
"""

from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

CHECKER = Path(__file__).resolve().parent / "check_invariant_scenario_counts.py"

# The two catalogs are built from these rosters so that every expectation below
# is derived from the fixture rather than re-encoding its size: adding a tag
# here moves the checker's reported totals and the assertions together.
INVARIANT_TAGS = ("INV-001", "INV-002")
SCENARIO_TAGS = ("S01", "S02")

INVARIANT_COUNT = len(INVARIANT_TAGS)
SCENARIO_COUNT = len(SCENARIO_TAGS)

# Counts no roster above can produce, for the cases that must be caught.
STALE_INVARIANT_COUNT = INVARIANT_COUNT + 3
STALE_SCENARIO_COUNT = SCENARIO_COUNT + 7

INVARIANTS_TEXT = (
    "# Invariant test index\n\n"
    "<!-- Generated by scripts/generate_invariants.py; do not edit. -->\n\n"
    "| ID      | Enforcement                        |\n"
    "| ------- | ----------------------------------- |\n"
    + "".join(
        f"| {tag} | tests in [`src/{tag}.rs`](../src/{tag}.rs) |\n" for tag in INVARIANT_TAGS
    )
)

SCENARIOS_TEXT = "# Design scenarios\n\n" + "".join(
    f"## {tag} — Scenario {tag}\n\nBody.\n\n" for tag in SCENARIO_TAGS
)


def git(root: Path, *arguments: str) -> None:
    subprocess.run(
        ["git", "-c", "commit.gpgSign=false", *arguments],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )


def run_checker(root: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(CHECKER)],
        cwd=root,
        check=False,
        capture_output=True,
        text=True,
    )


def fixture_root(
    directory: str,
    extra: dict[str, str] | None = None,
    *,
    omit_invariants: bool = False,
    invariants_text: str | None = None,
    scenarios_text: str | None = None,
) -> Path:
    """Build a synthetic repository with the two generated catalogs staged.

    `git ls-files` reads the index, so `git add` (no commit needed) is enough
    to make a fixture file "tracked" for the checker's own discovery; a file
    written but never added stays invisible, which is how the sibling-worktree
    test below proves untracked content is ignored.

    `invariants_text`/`scenarios_text` replace a catalog wholesale, for the
    cases that put a fenced example inside the catalog itself.
    """
    root = Path(directory)
    (root / "docs").mkdir(parents=True)
    if not omit_invariants:
        (root / "docs/invariants.md").write_text(
            INVARIANTS_TEXT if invariants_text is None else invariants_text,
            encoding="utf-8",
        )
    (root / "docs/scenarios.md").write_text(
        SCENARIOS_TEXT if scenarios_text is None else scenarios_text, encoding="utf-8"
    )
    for relative, text in (extra or {}).items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
    git(root, "init", "-q")
    git(root, "add", "-A")
    return root


class InvariantScenarioCountCheckerTests(unittest.TestCase):
    def test_no_stated_counts_passes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp, {"AGENTS.md": "# Guidance\n\nSee the catalog.\n"}
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn(
            f"{INVARIANT_COUNT} invariants, {SCENARIO_COUNT} scenarios", result.stdout
        )

    def test_accurate_stated_count_passes(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The catalog defines {INVARIANT_COUNT} invariants "
                        f"and {SCENARIO_COUNT} scenarios.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_stale_invariant_count_fails(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The catalog defines {STALE_INVARIANT_COUNT} invariants today.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("docs/spec/example.md:1", result.stdout)
        self.assertIn(f"{STALE_INVARIANT_COUNT} invariants", result.stdout)
        self.assertIn(f"current invariant catalog has {INVARIANT_COUNT}", result.stdout)

    def test_stale_scenario_count_phrase_fails(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp, {"README.md": f"scenario count: {STALE_SCENARIO_COUNT}\n"}
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("README.md:1", result.stdout)
        self.assertIn(f"current scenario catalog has {SCENARIO_COUNT}", result.stdout)

    def test_stale_count_wrapped_across_a_line_break_fails(self) -> None:
        """mdformat rewraps prose; a wrapped claim is still one claim."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The catalog currently defines {STALE_INVARIANT_COUNT}\n"
                        "invariants across the workspace.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("docs/spec/example.md:1", result.stdout)
        self.assertIn(f"{STALE_INVARIANT_COUNT} invariants", result.stdout)

    def test_number_and_noun_in_separate_paragraphs_is_not_a_count(self) -> None:
        """A blank line ends the statement; the noun below is a new sentence."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The sweep touched {STALE_INVARIANT_COUNT}\n\n"
                        "invariants are generated, never hand-written.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_count_inside_fenced_code_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"```text\n{STALE_INVARIANT_COUNT} invariants (example only)\n```\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_count_inside_a_tilde_fence_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"~~~\n{STALE_INVARIANT_COUNT} invariants (example only)\n~~~\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_count_inside_a_long_fence_holding_a_short_fence_is_ignored(self) -> None:
        """An inner ``` must not close an outer ````."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        "````markdown\n"
                        "```\n"
                        f"{STALE_INVARIANT_COUNT} invariants (example only)\n"
                        "```\n"
                        "````\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_count_inside_a_block_quoted_fence_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        "> ```text\n"
                        f"> {STALE_INVARIANT_COUNT} invariants (example only)\n"
                        "> ```\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_count_inside_a_list_nested_fence_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        "- Example:\n\n"
                        "  ```text\n"
                        f"  {STALE_INVARIANT_COUNT} invariants (example only)\n"
                        "  ```\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_invariant_identifier_is_not_mistaken_for_a_count(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {"docs/spec/example.md": f"See {INVARIANT_TAGS[-1]} for details.\n"},
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_scenario_reference_by_id_is_not_mistaken_for_a_count(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"See the {SCENARIO_TAGS[0]} scenario for the walkthrough.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_untracked_sibling_worktree_is_ignored(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(tmp)
            sibling = root / ".claude/worktrees/agent-phantom/docs/spec"
            sibling.mkdir(parents=True)
            (sibling / "phantom.md").write_text(
                f"The catalog defines {STALE_INVARIANT_COUNT} invariants.\n",
                encoding="utf-8",
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_invariant_citation_before_the_noun_is_not_a_count(self) -> None:
        """`INV-002 invariant` must not read as a stated count of 2.

        The identifier's digits sit directly before the noun, so only the
        lookbehind's hyphen rejection separates a required citation from a
        claim about the catalog. AGENTS.md mandates these citations, so the
        failure mode is the checker firing on the references it protects.
        """
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The {INVARIANT_TAGS[-1]} invariant covers the reconnect path.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_stale_count_in_a_nested_block_quote_fails(self) -> None:
        """A wrapped claim keeps its full quote prefix, not just one marker."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"> > The catalog defines {STALE_INVARIANT_COUNT}\n"
                        "> > invariants across the workspace.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn(f"{STALE_INVARIANT_COUNT} invariants", result.stdout)

    def test_fenced_scenario_heading_does_not_enlarge_the_catalog(self) -> None:
        """A documented example of the heading format names no scenario."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The catalog defines {SCENARIO_COUNT} scenarios.\n"
                    )
                },
                scenarios_text=(
                    SCENARIOS_TEXT
                    + "Scenarios are written like this:\n\n"
                    + "```markdown\n## S99 — Example heading\n```\n"
                ),
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn(f"{SCENARIO_COUNT} scenarios", result.stdout)

    def test_fenced_invariant_row_does_not_enlarge_the_catalog(self) -> None:
        """The same, for a fenced example of the invariant row format."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/spec/example.md": (
                        f"The catalog defines {INVARIANT_COUNT} invariants.\n"
                    )
                },
                invariants_text=(
                    INVARIANTS_TEXT
                    + "\nRows are written like this:\n\n"
                    + "```markdown\n| INV-999 | tests in [`src/x.rs`](../src/x.rs) |\n```\n"
                ),
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn(f"{INVARIANT_COUNT} invariants", result.stdout)

    def test_non_authoritative_planning_file_is_skipped(self) -> None:
        """A backlog quantity is a work item, not a claim about the catalog."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/agents/backlog.md": (
                        "# Work backlog\n\n"
                        "> **Non-authoritative planning scratchpad — do not review "
                        "for consistency.**\n\n"
                        f"- Draft {STALE_SCENARIO_COUNT} scenarios for the new flow.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_same_quantity_without_the_banner_still_fails(self) -> None:
        """Negative control: the exemption is the banner, not the filename."""
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(
                tmp,
                {
                    "docs/agents/backlog.md": (
                        "# Work backlog\n\n"
                        f"- Draft {STALE_SCENARIO_COUNT} scenarios for the new flow.\n"
                    )
                },
            )

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("docs/agents/backlog.md", result.stdout)

    def test_missing_invariants_catalog_fails_loudly(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            root = fixture_root(tmp, omit_invariants=True)

            result = run_checker(root)

        self.assertEqual(result.returncode, 1, result.stdout)
        self.assertIn("invariants.md", result.stdout)


if __name__ == "__main__":
    unittest.main()
