load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary")

rust_package()

rust_binary(
    name = "signalbox-cargo-bin-resolver",
    crate_root = "src/main.rs",
)

rust_test(
    name = "signalbox_cargo_bin_resolver_unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox-cargo-bin-resolver",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)
