load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_library")

rust_package()

rust_library(
    name = "signalbox_domain",
)

rust_test(
    name = "unit_tests",
    size = "small",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    crate = ":signalbox_domain",
    lint_config = ":cargo_lints",
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    deps = all_crate_deps(normal_dev = True),
)

rust_doc(
    name = "api_json",
    crate = ":signalbox_domain",
    rustdoc_flags = [
        "-Z",
        "unstable-options",
        "--output-format",
        "json",
    ],
    visibility = ["//:__pkg__"],
)
