load("@crates//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_binary", "rust_library")

filegroup(
    name = "fixtures",
    srcs = glob(["fixtures/**"]) + ["examples/repository.toml"],
    visibility = ["//:__subpackages__"],
)

rust_package(exports = [
    "Cargo.toml",
    "examples/repository.toml",
])

rust_library(
    name = "signalbox_convergence",
    crate_root = "src/lib.rs",
)

rust_binary(
    name = "signalbox-converge",
    crate_root = "src/main.rs",
    deps = [":signalbox_convergence"],
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox_convergence",
    crate_features = [],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_test(
    name = "signalbox_converge_unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox-converge",
    crate_features = [],
    data = [":fixtures"],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_env = {"CARGO_MANIFEST_DIR": "crates/convergence"},
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    # These tests execute host shell or process utilities.
    tags = ["external"],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_doc(
    name = "api_json",
    crate = ":signalbox_convergence",
    rustdoc_flags = [
        "-Z",
        "unstable-options",
        "--output-format",
        "json",
    ],
    visibility = ["//:__pkg__"],
)
