load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_library", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")

CRATE_FEATURES = ["test-support"]

rust_package()

rust_library(
    name = "signalbox_blob_store",
    srcs = glob(["src/*.rs"]),
    aliases = aliases(),
    crate_features = CRATE_FEATURES,
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//crates/domain:signalbox_domain"] + all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    size = "small",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    crate = ":signalbox_blob_store",
    lint_config = ":cargo_lints",
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    deps = all_crate_deps(normal_dev = True),
)

rust_doc(
    name = "api_json",
    crate = ":signalbox_blob_store",
    crate_features = CRATE_FEATURES,
    rustdoc_flags = [
        "-Z",
        "unstable-options",
        "--output-format",
        "json",
    ],
    visibility = ["//:__pkg__"],
)
