load("@rules_rust//rust:defs.bzl", "rust_doc_test", "rust_library", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:testing.bzl", "rust_quality_tests")

rust_package(exports = [])

rust_library(
    name = "signalbox_newtype",
    srcs = ["src/lib.rs"],
    edition = "2024",
    lint_config = ":cargo_lints",
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
)

rust_test(
    name = "unit_tests",
    size = "small",
    crate = ":signalbox_newtype",
    lint_config = ":cargo_lints",
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_newtype",
)

rust_quality_tests(documented_crates = [":signalbox_newtype"])
