load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "signalbox_newtype",
    srcs = ["src/lib.rs"],
    edition = "2024",
    rustc_flags = ["--forbid=unsafe_code"],
    visibility = ["//:__subpackages__"],
)

rust_test(
    name = "unit_tests",
    size = "small",
    crate = ":signalbox_newtype",
)
