load("//tooling/bazel:package.bzl", "rust_package")
load("//tooling/bazel:rust.bzl", "rust_library")
load("//tooling/bazel:testing.bzl", "rust_api_json", "rust_doc_test", "rust_integration_test", "rust_unit_test")

CRATE_FEATURES = [
    "default",
    "test-support",
]

rust_package()

rust_library(
    name = "signalbox_blob_store_s3",
    crate_features = CRATE_FEATURES,
    crate_root = "src/lib.rs",
    deps = [
        "//crates/blob-store:signalbox_blob_store",
        "//crates/domain:signalbox_domain",
    ],
)

rust_unit_test(
    name = "unit_tests",
    crate = ":signalbox_blob_store_s3",
    crate_features = CRATE_FEATURES,
    deps = ["//crates/blob-store:signalbox_blob_store"],
)

rust_api_json(
    name = "api_json",
    crate = ":signalbox_blob_store_s3",
    crate_features = CRATE_FEATURES,
)

rust_doc_test(
    name = "doc_tests",
    crate = ":signalbox_blob_store_s3",
    crate_features = [
        "default",
        "test-support",
    ],
)

rust_integration_test(
    name = "conformance",
    args = ["--test-threads=4"],
    srcs = glob(["tests/**/*.rs"]),
    crate_features = [
        "default",
        "test-support",
    ],
    crate_root = "tests/conformance.rs",
    data = glob(
        ["tests/**"],
        allow_empty = True,
        exclude = ["tests/**/*.rs"],
    ) + [],
    rustc_env = {"CARGO_MANIFEST_DIR": "crates/blob-store-s3"},
    deps = [
        "//crates/blob-store:signalbox_blob_store",
        "//crates/blob-store-s3:signalbox_blob_store_s3",
        "//crates/domain:signalbox_domain",
    ],
)
