load("@crates//:defs.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_doc", "rust_library", "rust_test")
load("//tooling/bazel:package.bzl", "rust_package")

rust_package(exports = [
    "Cargo.toml",
    "tests/fixtures/example.json",
])

rust_library(
    name = "signalbox_web_contract",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [
        "tests/fixtures/example.json",
        "tests/fixtures/session-closed-rates.json",
    ],
    crate_features = [],
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//crates/application:signalbox_application"] + all_crate_deps(normal = True),
)

rust_binary(
    name = "generate-web-contract",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    compile_data = [
        "tests/fixtures/example.json",
        "tests/fixtures/session-closed-rates.json",
    ],
    crate_features = [],
    crate_root = "src/bin/generate-web-contract.rs",
    edition = crate_edition(),
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro = True),
    rustc_env_files = [":cargo_environment"],
    rustc_flags = [
        "--forbid=unsafe_code",
        "--deny=warnings",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":signalbox_web_contract",
        "//crates/application:signalbox_application",
    ] + all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":signalbox_web_contract",
    crate_features = [],
    data = [
        "tests/fixtures/example.json",
        "//:web_contract_fixtures",
    ],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_env = {"CARGO_MANIFEST_DIR": "crates/web-contract"},
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_test(
    name = "generate_web_contract_unit_tests",
    size = "large",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    args = ["--test-threads=16"],
    crate = ":generate-web-contract",
    crate_features = [],
    data = [
        "Cargo.toml",
        "//:Cargo.toml",
        "//:web_contract_fixtures",
    ],
    lint_config = ":cargo_lints",
    proc_macro_deps = [] + all_crate_deps(proc_macro_dev = True),
    rustc_env = {"CARGO_MANIFEST_DIR": "crates/web-contract"},
    rustc_flags = [
        "--deny=warnings",
        "--forbid=unsafe_code",
    ],
    deps = [] + all_crate_deps(normal_dev = True),
)

rust_doc(
    name = "api_json",
    crate = ":signalbox_web_contract",
    rustdoc_flags = [
        "-Z",
        "unstable-options",
        "--output-format",
        "json",
    ],
    visibility = ["//:__pkg__"],
)
